//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC12ControlStrip25FunctionRowViewController.h"

@class NSButton;

@interface _TtC12ControlStrip8CloseBox : _TtC12ControlStrip25FunctionRowViewController
{
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: connection
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)closeAction:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic, retain) NSButton *closeButton; // @synthesize closeButton;

@end

