//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC12ControlStrip18ControlStripButton.h"

@interface _TtC12ControlStrip12SliderButton : _TtC12ControlStrip18ControlStripButton
{
    // Error parsing type: , name: popover
    // Error parsing type: , name: functionRow
    // Error parsing type: , name: isPresented
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didTriggerPressGestureRecognizer:(id)arg1;
- (void)didTriggerClickGestureRecognizer:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)accessibilityPerformPress;

@end

