//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12ControlStrip7Display : _TtCs12_SwiftObject
{
    // Error parsing type: , name: source
    // Error parsing type: , name: mode
    // Error parsing type: , name: needsNotification
    // Error parsing type: , name: _brightness
    // Error parsing type: , name: display
    // Error parsing type: , name: isBuiltIn
}

@end

