//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC12ControlStrip12SliderButton.h"

@interface _TtC12ControlStrip12VolumeButton : _TtC12ControlStrip12SliderButton
{
    // Error parsing type: , name: display
    // Error parsing type: , name: lastUpdate
    // Error parsing type: , name: addedObserver
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)audioDidChange:(id)arg1;
- (void)dealloc;

@end

