//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PPRoutineSupport : NSObject
{
}

+ (id)locationsOfInterestVisitiedBetweenStartDate:(id)arg1 endDate:(id)arg2;
+ (void)fetchLocationsOfInterestMapItemsVisitiedBetweenStartDate:(id)arg1 endDate:(id)arg2 withHandler:(CDUnknownBlockType)arg3;
+ (void)importCoreRoutineData;

@end

