//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <SiriClientFlow/NSObject-Protocol.h>

@class AFPeerInfo, NSBundle, NSString, NSURL, SABaseCommand;

@protocol AFServiceHelper <NSObject>
- (AFPeerInfo *)peerInfoForCurrentCommand;
- (BOOL)isTimeoutSuspended;
- (void)handleCommand:(SABaseCommand *)arg1 completion:(void (^)(SABaseCommand *, NSError *))arg2;
- (BOOL)isDeviceLockedWithPasscode;
- (NSString *)assistantLocalizedStringForKey:(NSString *)arg1 table:(NSString *)arg2 bundle:(NSBundle *)arg3;
- (void)dismissAssistant;
- (BOOL)openSensitiveURL:(NSURL *)arg1;
@end

