//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AMSCardEnrollment : NSObject
{
}

+ (id)_paymentServicesMerchantURLPromise;
+ (id)_currentIdentifier;
+ (id)_cardEligibilityStatusForCountryCode:(id)arg1;
+ (void)updateAutoEnrollmentIdentifier;
+ (BOOL)shouldUseAutoEnrollmentWithPercentage:(double)arg1 sessionDuration:(double)arg2;
+ (BOOL)shouldAttemptAutoEnrollmentWithCountryCode:(id)arg1;
+ (void)clearAutoEnrollmentIdentifier;
+ (BOOL)shouldAttemptAutoEnrollment;
+ (id)paymentServicesMerchantURL;
+ (BOOL)isBiometricACLUpgradeRequired;

@end

