//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface AMSFamilyInfoLookupResult : NSObject
{
    BOOL _cached;
    NSArray *_familyMembers;
}

+ (id)_familyMembersFromDictionaryRepresentation:(id)arg1;
@property(readonly) NSArray *familyMembers; // @synthesize familyMembers=_familyMembers;
@property(readonly, getter=isCached) BOOL cached; // @synthesize cached=_cached;
- (void).cxx_destruct;
- (id)description;
@property(readonly) NSDictionary *dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1 cached:(BOOL)arg2;

@end

