//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store22BaseCollectionViewCell.h"

@interface _TtC9App_Store37ClientControlButtonCollectionViewCell : _TtC9App_Store22BaseCollectionViewCell
{
    // Error parsing type: , name: buttonAction
    // Error parsing type: , name: buttonView
}

- (void).cxx_destruct;
- (id)accessibilityRole;
- (void)prepareForReuse;
- (void)layout;
- (void)performButtonAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

