//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store24BaseNavigationController.h"

@interface _TtC9App_Store24FlowNavigationController : _TtC9App_Store24BaseNavigationController
{
    // Error parsing type: , name: flowController
    // Error parsing type: , name: actionRunner
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

