//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store30MediumLockupCollectionViewCell.h"

@interface _TtC9App_Store33PurchasesLockupCollectionViewCell : _TtC9App_Store30MediumLockupCollectionViewCell
{
    // Error parsing type: , name: moreButton
    // Error parsing type: , name: trackingArea
}

- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)didClickMoreButton:(id)arg1;
- (void)layout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

