//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC9App_StoreP33_5C5B326F1A1DFF3EE6D3119519682A0F16PageSwipeGesture : _TtCs12_SwiftObject
{
    // Error parsing type: , name: target
    // Error parsing type: , name: interpolator
    // Error parsing type: , name: isInterrupted
    // Error parsing type: , name: amount
}

@end

