//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC9App_Store15BaseSidebarItem : _TtCs12_SwiftObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: image
    // Error parsing type: , name: viewController
    // Error parsing type: , name: itemView.storage
    // Error parsing type: , name: badgeValue
    // Error parsing type: , name: badgeAccessibilityLabel
    // Error parsing type: , name: identifier
}

@end

