//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store22BaseCollectionViewCell.h"

@interface _TtC9App_Store35ScreenshotsLockupCollectionViewCell : _TtC9App_Store22BaseCollectionViewCell
{
    // Error parsing type: , name: screenshotsLockupView
}

- (void).cxx_destruct;
- (id)accessibilityCustomActions;
- (id)accessibilityChildren;
- (id)accessibilityTitle;
- (id)accessibilityLabel;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
- (void)prepareForReuse;
- (void)layout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

