//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store18SettingsController.h"

@class NSTextField, _TtC9App_Store18PreferenceCheckbox, _TtC9App_Store18PreferenceDropdown;

@interface _TtC9App_Store26PasswordSettingsController : _TtC9App_Store18SettingsController
{
    // Error parsing type: , name: touchIdCheckbox
    // Error parsing type: , name: passwordIntroField
    // Error parsing type: , name: purchasesPasswordDropdownControl
    // Error parsing type: , name: freePasswordDropdownControl
}

- (void).cxx_destruct;
- (void)globalTouchIdSettingChanged;
- (void)dealloc;
- (id)init;
@property(nonatomic, retain) _TtC9App_Store18PreferenceDropdown *freePasswordDropdownControl; // @synthesize freePasswordDropdownControl;
@property(nonatomic, retain) _TtC9App_Store18PreferenceDropdown *purchasesPasswordDropdownControl; // @synthesize purchasesPasswordDropdownControl;
@property(nonatomic, retain) NSTextField *passwordIntroField; // @synthesize passwordIntroField;
@property(nonatomic, retain) _TtC9App_Store18PreferenceCheckbox *touchIdCheckbox; // @synthesize touchIdCheckbox;

@end

