//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store26BaseCollectionReusableView.h"

@interface _TtC9App_Store21AppAdoptionHeaderView : _TtC9App_Store26BaseCollectionReusableView
{
    // Error parsing type: , name: titleLabelView
    // Error parsing type: , name: callOutView
}

- (void).cxx_destruct;
- (void)layout;
@property(nonatomic, readonly) struct CGRect jet_layoutFrame;
- (id)initWithFrame:(struct CGRect)arg1;

@end

