//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store14BackgroundView.h"

@interface _TtC9App_StoreP33_AA4463CA2B5C302A677825E4B852A89022ScrollerHitPassingView : _TtC9App_Store14BackgroundView
{
    // Error parsing type: , name: scrollerProvider
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) BOOL mouseDownCanMoveWindow;
- (id)hitTest:(struct CGPoint)arg1;

@end

