//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC9App_StoreP33_28979371C85A026E043D05A550BD5A9521ActionBlockTrampoline : _TtCs12_SwiftObject
{
    // Error parsing type: , name: actionBlock
}

- (void)perform:(id)arg1;

@end

