//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store13ClickableView.h"

@interface _TtC9App_StoreP33_5C5B326F1A1DFF3EE6D3119519682A0F12PagingButton : _TtC9App_Store13ClickableView
{
    // Error parsing type: , name: arrowView
    // Error parsing type: , name: direction
    // Error parsing type: , name: arrowCenterY
}

- (void).cxx_destruct;
- (id)accessibilityChildren;
- (BOOL)isAccessibilityElement;
- (void)layout;
- (BOOL)isFlipped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

