//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store14ScrollObserver.h"

@interface _TtCC9App_Store33RevealingNavigationBackgroundViewP33_607F32060438191AEBAC71B3178B293B20RevealScrollObserver : _TtC9App_Store14ScrollObserver
{
    // Error parsing type: , name: owner
}

@end

