//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC9App_Store13BaseBootstrap : _TtCs12_SwiftObject
{
    // Error parsing type: , name: diagnostics
    // Error parsing type: , name: networkObserverDelegate
    // Error parsing type: , name: pendingEvents
    // Error parsing type: , name: isBootstrapping
}

@end

