//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store14BackgroundView.h"

@interface _TtC9App_Store10BundleView : _TtC9App_Store14BackgroundView
{
    // Error parsing type: , name: iconStyle
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: items
    // Error parsing type: , name: itemReusePool
}

- (void).cxx_destruct;
- (struct JEMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;
- (void)layout;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

