//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC9App_Store14BackgroundView.h"

@interface _TtC9App_StoreP33_00EFC65CCC83C0F4FCCF142FFBFA6E8A9BadgeView : _TtC9App_Store14BackgroundView
{
    // Error parsing type: , name: label
    // Error parsing type: , name: accessibilityLabelOverride
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)accessibilityValue;
- (id)accessibilityChildren;
- (id)accessibilityLabel;
- (BOOL)accessibilityShouldUseUniqueId;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
- (void)layout;
@property(nonatomic, readonly) struct CGSize fittingSize;
@property(nonatomic, readonly) BOOL allowsVibrancy;

@end

