//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSURL;

@interface AKELData : NSObject
{
    NSURL *_url;
    NSDate *_timestamp;
    NSDictionary *_signatureExceptionData;
    NSDictionary *_timestampExceptionData;
}

- (void).cxx_destruct;
- (BOOL)isKextAllowedWithoutSecureTimestamp:(id)arg1;
- (id)findLegacyKextBundleID:(id)arg1;
- (BOOL)isLegacyKextAllowed:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)init;
- (void)reloadIfNecessary;
- (void)doReload;

@end

