//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IMDaemonCore/IMDCKMockRecordZone.h>

@interface IMDCKMockRecordKeyZone : IMDCKMockRecordZone
{
}

- (void)_handleFetchingExitRecordOperation:(id)arg1;
- (void)_handleWritingCloudKitMetrics:(id)arg1;
- (void)handleOperation:(id)arg1;
- (BOOL)_operationIsCloudKitMetricsOperation:(id)arg1;

@end

