//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIAlertAction.h>

@class HFTVInputControlItemValue;

@interface HUQuickControlInputSourceAction : UIAlertAction
{
    HFTVInputControlItemValue *_controlItemValue;
}

+ (id)actionWithInputSourceControlItemValue:(id)arg1 selectionBlock:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) HFTVInputControlItemValue *controlItemValue; // @synthesize controlItemValue=_controlItemValue;
- (void).cxx_destruct;

@end

