//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <NetworkExtension/NEInternetNexus.h>

@interface NEIPsecNexus : NEInternetNexus
{
}

- (void)setRemotePacketProxy:(id)arg1;
- (BOOL)setDefaultInputHandler:(struct nw_protocol *)arg1;
- (id)initWithName:(id)arg1 delegate:(id)arg2 shouldCreateKernelChannel:(BOOL)arg3;

@end

