//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUUID, NWBrowseDescriptor, NWParameters;

@interface NENexusBrowse : NSObject
{
    NWBrowseDescriptor *_descriptor;
    NWParameters *_parameters;
    NSUUID *_clientIdentifier;
}

@property(retain, nonatomic) NSUUID *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
@property(retain, nonatomic) NWParameters *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NWBrowseDescriptor *descriptor; // @synthesize descriptor=_descriptor;
- (void).cxx_destruct;

@end

