//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <NetworkExtension/NENexusFlow.h>

@class NWPath;

@interface NENexusPathFlow : NENexusFlow
{
    NWPath *_path;
}

@property(retain) NWPath *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (id)clientIdentifier;
- (id)parameters;
- (id)endpoint;
- (id)initWithPath:(id)arg1;

@end

