//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ConversationKit/NSObject-Protocol.h>

__attribute__((visibility("hidden")))
@interface _TtC15ConversationKit14TapInteraction : NSObject <NSObject>
{
    // Error parsing type: , name: view
    // Error parsing type: , name: tapGestureRecognizer
}

- (void).cxx_destruct;
- (void)handleRecognizer:(id)arg1;
- (id)init;
@property(nonatomic) long long numberOfTapsRequired;

@end

