//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ConversationKit/_TtC15ConversationKit23PlatformDisplayLinkBase.h>

@interface _TtC15ConversationKit19PlatformDisplayLink : _TtC15ConversationKit23PlatformDisplayLinkBase
{
    // Error parsing type: , name: observers
    // Error parsing type: , name: isRunning
}

@end

