//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ConversationKit/CNKFaceTimeMultiwayConversationViewController.h>

@interface CNKFaceTimeMultiwayConversationViewController (ConversationKit)
- (void)inCallControlsDragController:(id)arg1 didEndDragAt:(long long)arg2;
- (void)inCallControlsDragController:(id)arg1 didStartDragTo:(long long)arg2;
- (void)inCallControlsDragController:(id)arg1 willStartDragFrom:(long long)arg2;
- (long long)inCallControlsDragControllerShortestState:(id)arg1;
@end

