//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface CNVCardReadingOptions : NSObject
{
    unsigned long long _contactLimit;
    NSArray *_propertiesToFetch;
    unsigned long long _maximumValueLength;
}

@property(nonatomic) unsigned long long maximumValueLength; // @synthesize maximumValueLength=_maximumValueLength;
@property(copy, nonatomic) NSArray *propertiesToFetch; // @synthesize propertiesToFetch=_propertiesToFetch;
@property(nonatomic) unsigned long long contactLimit; // @synthesize contactLimit=_contactLimit;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

