//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDS/IDSTransactionLogTask.h>

@interface IDSTransactionLogSyncTask : IDSTransactionLogTask
{
    CDUnknownBlockType _batchProcessingBlock;
    CDUnknownBlockType _knownRecordIDsFromList;
    BOOL _shouldContinueFromLastSyncPoint;
}

@property(nonatomic) BOOL shouldContinueFromLastSyncPoint; // @synthesize shouldContinueFromLastSyncPoint=_shouldContinueFromLastSyncPoint;
@property(copy, nonatomic) CDUnknownBlockType knownRecordIDsFromList; // @synthesize knownRecordIDsFromList=_knownRecordIDsFromList;
@property(copy, nonatomic) CDUnknownBlockType batchProcessingBlock; // @synthesize batchProcessingBlock=_batchProcessingBlock;
- (void).cxx_destruct;

@end

