//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC8PIPAgent5AgentP33_E07A48E4194B573D7A6A8C39104DB7B27Clients : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _connections
    // Error parsing type: , name: _controllers
    // Error parsing type: , name: _routing
    // Error parsing type: , name: _deathTimer
}

@end

