//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SiriCoreWiFiManagerClient : NSObject
{
    int _rssi;
    int _snr;
}

- (void)registerOneShotEnabledHandler:(CDUnknownBlockType)arg1;
- (void)acquireWiFiAssertion:(long long)arg1;
- (void)releaseWiFiAssertion;
- (BOOL)isWifiEnabled;
- (BOOL)hasAssociatedNetworkWithRSSI:(int *)arg1 andSNR:(int *)arg2 andPhyMode:(id *)arg3 andChannelInfo:(id *)arg4 isCaptive:(char *)arg5;
- (void)dealloc;
- (id)init;

@end

