//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Contacts/CNContact.h>

@interface CNContact (IMAssistantCore)
- (id)__im_assistant_allIMHandles;
- (id)__im_assistant_allValidPersonOptionsWithAccount:(id)arg1;
- (id)__im_assistant_matchingNormalizedHandlesForType:(long long)arg1 andLabel:(id)arg2 forCountryCode:(id)arg3;
- (BOOL)__im_assistant_labeledContactValue:(id)arg1 matchesPersonHandleLabel:(id)arg2;
- (id)__im_assistant_normalizedHandleForAnonymousContactUsingCountryCode:(id)arg1;
@end

