//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMAssistantMessageAttributeOptions : NSObject
{
    unsigned long long _attributes;
}

+ (id)optionsWithAttributes:(unsigned long long)arg1 sanitizer:(id)arg2;
+ (id)optionsWithAttributes:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long attributes; // @synthesize attributes=_attributes;
@property(readonly, nonatomic) BOOL includeUnread;
@property(readonly, nonatomic) BOOL includeRead;
- (id)initWithAttributes:(unsigned long long)arg1 sanitizer:(id)arg2;
- (id)initWithAttributes:(unsigned long long)arg1;

@end

