//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MRT.MRTFileInfo : NSObject
{
    // Error parsing type: , name: fileName
    // Error parsing type: , name: fileType
    // Error parsing type: , name: fileSize
    // Error parsing type: , name: fileHash
    // Error parsing type: , name: createdTime
    // Error parsing type: , name: modifiedTime
    // Error parsing type: , name: customDataHash
    // Error parsing type: , name: customDataString
    // Error parsing type: , name: bundleId
    // Error parsing type: , name: teamId
    // Error parsing type: , name: isCodeSigned
    // Error parsing type: , name: isCodeSignatureValid
    // Error parsing type: , name: cdHash
    // Error parsing type: , name: cdHashType
    // Error parsing type: , name: fileSignedTime
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

