//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "MRT.FileAndAgentFamily.h"

@interface MRT.Familyb918164 : MRT.FileAndAgentFamily
{
    // Error parsing type: , name: plistStrings
    // Error parsing type: , name: scriptStringsA
    // Error parsing type: , name: scriptStringsB
    // Error parsing type: , name: scriptStringsC
    // Error parsing type: , name: oldStrings
    // Error parsing type: , name: qemuStrings
    // Error parsing type: , name: qemuKnownPaths
}

@end

