//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "MRT.FileAndAgentFamily.h"

@interface MRT.Family127eaa6 : MRT.FileAndAgentFamily
{
    // Error parsing type: , name: maxFileSize
    // Error parsing type: , name: importStringA
    // Error parsing type: , name: importStringB
    // Error parsing type: , name: importStringC
    // Error parsing type: , name: endMarkerString
    // Error parsing type: , name: payloadString1A
    // Error parsing type: , name: payloadString1AencodingA
    // Error parsing type: , name: payloadString1AencodingB
    // Error parsing type: , name: payloadString1AencodingC
    // Error parsing type: , name: payloadString1B
    // Error parsing type: , name: payloadString1BencodingA
    // Error parsing type: , name: payloadString1BencodingB
    // Error parsing type: , name: payloadString1BencodingC
    // Error parsing type: , name: payloadString2
    // Error parsing type: , name: payloadString2encodingA
    // Error parsing type: , name: payloadString2encodingB
    // Error parsing type: , name: payloadString2encodingC
}

@end

