//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "MRT.FileAndAgentFamily.h"

@interface MRT.ATG15FamilyB : MRT.FileAndAgentFamily
{
    // Error parsing type: , name: userPlistPath
    // Error parsing type: , name: rootPlistPath
    // Error parsing type: , name: userPathMatchString
    // Error parsing type: , name: rootPathMatchString
}

@end

