//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <FinderKit/FI_TIconOrGalleryCollectionView.h>

__attribute__((visibility("hidden")))
@interface FI_TIconCollectionView : FI_TIconOrGalleryCollectionView
{
}

- (id)popoverAnchorViewForNode:(const struct TFENode *)arg1;
- (id)iconViewForNode:(const struct TFENode *)arg1;
- (id)iconViewForIndexPath:(id)arg1;
- (void)setCollectionViewDelegate:(id)arg1;
- (id)collectionViewDelegate;

@end

