//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <FinderKit/FI_ISpotlightAttributesExtractor.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface FI_TColumnPreviewSpotlightAttributesExtractor : FI_ISpotlightAttributesExtractor
{
    struct TNSRef<NSArray<NSString *>, void> _queryAttributes;
    struct mutex _queryAttributesLock;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *queryAttributes; // @dynamic queryAttributes;
- (id)attributeNamesForNode:(const struct TFENode *)arg1;
- (id)init;

@end

