//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP18Feedback_Assistant21FBARichTextExportable_-Protocol.h"

@class FBAQuestionAnswerPair, NSAttributedString, NSString;

@interface _TtC18Feedback_Assistant18FBAFilePromiseStub : NSObject <_TtP18Feedback_Assistant21FBARichTextExportable_>
{
    // Error parsing type: , name: name
    // Error parsing type: , name: status
    // Error parsing type: , name: questionAnswerPairRepresentation.storage
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) FBAQuestionAnswerPair *questionAnswerPairRepresentation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) long long status; // @synthesize status;
@property(nonatomic, retain) NSString *name; // @synthesize name;
@property(nonatomic, readonly) NSString *description;
- (id)initWithName:(id)arg1 status:(long long)arg2;
- (id)initWithJSONObject:(id)arg1;
@property(nonatomic, readonly) NSAttributedString *richTextExportRepresentation;

@end

