//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMCKPadding : NSObject
{
}

+ (id)paddingForMessageOfSize:(long long)arg1;
+ (long long)_paddingForType:(int)arg1 originalSize:(long long)arg2 error:(struct __CFError **)arg3;
+ (id)_randomDataWithLength:(long long)arg1;

@end

