//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;

@interface IMGroupBlacklistManager : NSObject
{
    NSDate *_lastModifiedDate;
}

+ (id)sharedInstance;
+ (id)groupsBlacklistFilename;
@property(retain) NSDate *lastModifiedDate; // @synthesize lastModifiedDate=_lastModifiedDate;
- (void).cxx_destruct;
- (void)reloadIfNeeded;
- (void)_updateLastModifiedDate:(id)arg1;
- (void)loadFromFile:(id)arg1;
- (void)loadData;
- (void)save;
- (BOOL)isFeatureDisabled;
- (BOOL)isGroupInBlacklist:(id)arg1;
- (void)blacklistGroupId:(id)arg1;
- (BOOL)hasFileChanged;
- (id)initFromFile:(id)arg1;
- (id)init;

@end

