//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (IMSingleton)
+ (BOOL)isSingleton;
+ (BOOL)replaceSingletonWithSubclass:(id)arg1;
+ (BOOL)isSingletonOverridden;
+ (id)overriddenSingleton;
+ (void)replaceSingletonWithObject:(id)arg1;
+ (void)removeSingletonOverride;
+ (void)overrideSingletonWithObject:(id)arg1;
+ (id)singletonOverride;
+ (id)_createSingleton__im;
- (BOOL)__isSingletonProxy__im;
@end

