//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/NSObject-Protocol.h>

@class NFFieldNotification, NFReaderSession, NFTechnologyEvent, NSArray;

@protocol NFReaderSessionDelegate <NSObject>

@optional
- (void)readerSession:(NFReaderSession *)arg1 externalReaderFieldNotification:(NFFieldNotification *)arg2;
- (void)readerSession:(NFReaderSession *)arg1 externalReaderFieldEvent:(NFTechnologyEvent *)arg2;
- (void)readerSessionDidEndUnexpectedly:(NFReaderSession *)arg1;
- (void)readerSession:(NFReaderSession *)arg1 didDetectTags:(NSArray *)arg2;
@end

