//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface PDDeviceRegistrationTask : NSObject
{
    BOOL _shouldForce;
    NSMutableArray *_completionHandlers;
    NSString *_reason;
}

@property(nonatomic) BOOL shouldForce; // @synthesize shouldForce=_shouldForce;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSMutableArray *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
- (void).cxx_destruct;
- (id)init;

@end

