//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PDXPCServiceExportedInterface-Protocol.h>

@class NSString;

@protocol PDDeviceRegistrationServiceExportedInterface <PDXPCServiceExportedInterface>
- (void)performDeviceRegistrationForReason:(NSString *)arg1 actionType:(long long)arg2 completion:(void (^)(unsigned long long))arg3;
@end

