//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@class PDScheduledActivityCriteria;
@protocol NSObject><NSSecureCoding;

@interface PDScheduledActivityRegistration : NSObject <NSSecureCoding>
{
    PDScheduledActivityCriteria *_activityCriteria;
    id <NSObject><NSSecureCoding> _activityContext;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) id <NSObject><NSSecureCoding> activityContext; // @synthesize activityContext=_activityContext;
@property(readonly, nonatomic) PDScheduledActivityCriteria *activityCriteria; // @synthesize activityCriteria=_activityCriteria;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqualToScheduledActivityRegistration:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithActivityCriteria:(id)arg1 activityContext:(id)arg2;

@end

