//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PDXPCServiceExportedInterface-Protocol.h>

@class NSData, NSString;

@protocol PDTrustedDeviceEnrollmentInfoProviderExportedInterface <PDXPCServiceExportedInterface>
- (void)trustedDeviceEnrollmentSignatureForDevice:(unsigned long long)arg1 accountDSID:(NSString *)arg2 sessionData:(NSData *)arg3 handler:(void (^)(NSString *, unsigned long long, NSData *, NSError *))arg4;
- (void)trustedDeviceEnrollmentInfoWithHandler:(void (^)(PKTrustedDeviceEnrollmentInfo *, PKTrustedDeviceEnrollmentInfo *))arg1;
@end

