//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PKAccountWebServiceRequest.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@class NSString, NSURL, PKAccountVirtualCardEncryptionFields;

@interface PKAccountWebServiceCreateVirtualCardRequest : PKAccountWebServiceRequest <NSSecureCoding>
{
    NSString *_accountIdentifier;
    NSURL *_baseURL;
    long long _type;
    PKAccountVirtualCardEncryptionFields *_encryptionFields;
}

@property(retain, nonatomic) PKAccountVirtualCardEncryptionFields *encryptionFields; // @synthesize encryptionFields=_encryptionFields;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(copy, nonatomic) NSString *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
- (void).cxx_destruct;
- (id)_urlRequestWithAppleAccountInformation:(id)arg1;

@end

