//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PKAccountWebServiceResponse.h>

@class NSData, NSString;

@interface PKAccountWebServiceTermsDataResponse : PKAccountWebServiceResponse
{
    NSData *_termsData;
    NSString *_termsDataFileName;
}

@property(copy, nonatomic) NSString *termsDataFileName; // @synthesize termsDataFileName=_termsDataFileName;
@property(retain, nonatomic) NSData *termsData; // @synthesize termsData=_termsData;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;

@end

