//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSCopying-Protocol.h>
#import <PassKitCore/NSSecureCoding-Protocol.h>

@interface PKAccountPreferences : NSObject <NSSecureCoding, NSCopying>
{
    unsigned long long _rewardsRedemptionType;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) unsigned long long rewardsRedemptionType; // @synthesize rewardsRedemptionType=_rewardsRedemptionType;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

