//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PKAccountWebServiceResponse.h>

@class CNContact;

@interface PKAccountWebServiceAccountUserInfoResponse : PKAccountWebServiceResponse
{
    CNContact *_userInfo;
}

@property(readonly, nonatomic) CNContact *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (id)_stringValueFromDictionary:(id)arg1 key:(id)arg2 isOptional:(BOOL)arg3;
- (id)initWithData:(id)arg1;

@end

