//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@class NSData, NSDictionary, PKContact, PKPeerPaymentQuote;

@interface PKAuthorizedPeerPaymentQuote : NSObject <NSSecureCoding>
{
    PKPeerPaymentQuote *_peerPaymentQuote;
    PKContact *_contact;
    NSData *_transactionData;
    NSDictionary *_certificates;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) NSDictionary *certificates; // @synthesize certificates=_certificates;
@property(readonly, nonatomic) NSData *transactionData; // @synthesize transactionData=_transactionData;
@property(retain, nonatomic) PKContact *contact; // @synthesize contact=_contact;
@property(readonly, nonatomic) PKPeerPaymentQuote *peerPaymentQuote; // @synthesize peerPaymentQuote=_peerPaymentQuote;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithQuote:(id)arg1 transactionData:(id)arg2 certificates:(id)arg3;

@end

