//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PKPaymentDataItem.h>

@class PKDisbursementApplicationInformation;

@interface PKDisbursementApplicationInformationDataItem : PKPaymentDataItem
{
    PKDisbursementApplicationInformation *_applicationInformation;
}

+ (long long)dataType;
@property(retain, nonatomic) PKDisbursementApplicationInformation *applicationInformation; // @synthesize applicationInformation=_applicationInformation;
- (void).cxx_destruct;
- (BOOL)isValidWithError:(id *)arg1;
- (id)initWithModel:(id)arg1;

@end

