//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/NSObject-Protocol.h>
#import <PassKitCore/NSSecureCoding-Protocol.h>

@class CLLocation, NSDictionary;

@protocol PKPaymentMarketGeoFence <NSObject, NSSecureCoding>
- (double)distanceFromLocation:(CLLocation *)arg1;
- (BOOL)containsLocation:(CLLocation *)arg1;
- (id)initWithDictionary:(NSDictionary *)arg1;
@end

