//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PassKitCore/PKRemoteAssetManifestItem.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@class NSString;

@interface PKRemoteCloudStoreAssetManifestItem : PKRemoteAssetManifestItem <NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
- (void)downloadAssetWithCloudStoreCoordinatorDelegate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (unsigned long long)itemType;
@property(readonly, nonatomic) NSString *recordName;

@end

