//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@interface PKWebServiceContext : NSObject <NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
+ (id)contextWithArchive:(id)arg1 error:(id *)arg2;
+ (id)contextWithArchive:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)archiveAtPath:(id)arg1 error:(id *)arg2;
- (void)archiveAtPath:(id)arg1;

@end

