//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface EARKeywordFinderResult : NSObject
{
    NSArray *_correctedUtterances;
}

@property(readonly, copy, nonatomic) NSArray *correctedUtterances; // @synthesize correctedUtterances=_correctedUtterances;
- (void).cxx_destruct;
- (id)description;
- (id)_initWithCorrectedUtterances:(id)arg1;

@end

