//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@class NSColor, NSFont, NSImage;

@interface CalcButtonCell : NSButtonCell
{
    BOOL isActiveOperation;
    NSColor *_textColor;
    NSFont *_textFont;
    NSImage *_normalButtonImage;
    NSImage *_disabledButtonImage;
}

@property(retain, nonatomic) NSImage *disabledButtonImage; // @synthesize disabledButtonImage=_disabledButtonImage;
@property(retain, nonatomic) NSImage *normalButtonImage; // @synthesize normalButtonImage=_normalButtonImage;
@property(retain, nonatomic) NSFont *textFont; // @synthesize textFont=_textFont;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property BOOL isActiveOperation; // @synthesize isActiveOperation;
- (void)drawFocusRingMaskWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawBezelWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (int)fontSizeForString:(id)arg1;
- (double)widthOfString:(id)arg1 withFont:(id)arg2;
- (id)initTextCell:(id)arg1;
- (void)loadColors;
- (void)updateImage:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

