//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SOAlertsHelper;

@interface ApplicationAlertsHelper : NSObject
{
    SOAlertsHelper *_alerts;
}

+ (id)sharedInstance;
@property(retain) SOAlertsHelper *alerts; // @synthesize alerts=_alerts;
- (void).cxx_destruct;
- (id)init;

@end

