//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSApplication.h>

@interface NSApplication (Scripting)
- (id)valueInScriptTextChatsWithName:(id)arg1;
- (id)valueInScriptTextChatsWithUniqueID:(id)arg1;
- (id)objectInScriptTextChatsAtIndex:(unsigned long long)arg1;
- (id)scriptTextChats;
- (id)valueInScriptChatsWithName:(id)arg1;
- (id)valueInScriptChatsWithUniqueID:(id)arg1;
- (id)objectInScriptChatsAtIndex:(unsigned long long)arg1;
- (id)scriptChats;
- (id)valueInScriptFileTransfersWithUniqueID:(id)arg1;
- (id)objectInScriptFileTransfersAtIndex:(unsigned long long)arg1;
- (id)scriptFileTransfers;
- (id)valueInServicesWithName:(id)arg1;
- (id)valueInServicesWithUniqueID:(id)arg1;
- (id)services;
- (id)valueInBuddiesWithUniqueID:(id)arg1;
- (id)valueInBuddiesWithName:(id)arg1;
- (id)buddies;
- (id)myImage;
- (void)setMyImage:(id)arg1;
- (id)myIdleTime;
- (id)myStatusMessage;
- (void)setMyStatusMessage:(id)arg1;
- (id)myStatus;
- (void)setMyStatus:(id)arg1;
- (void)inviteScriptCommand:(id)arg1;
- (void)storeRecentPictureCommand:(id)arg1;
- (void)showChatChooserCommand:(id)arg1;
- (void)logoutScriptCommand:(id)arg1;
- (void)loginScriptCommand:(id)arg1;
@end

