//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSMenu.h>

@interface NSMenu (MessagesKitAdditions)
- (void)_openMessages:(id)arg1;
- (void)_newMessage:(id)arg1;
- (void)_openRecentChat:(id)arg1;
- (void)appendOpenMessages;
- (void)appendNewMessage;
- (BOOL)appendUnreadChats;
- (void)appendSeparator;
- (void)endMessagesMenu;
- (void)beginMessagesMenu;
@end

