//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface People : NSObject
{
}

+ (BOOL)blockPersonWithIMHandles:(id)arg1 inWindow:(id)arg2;
+ (void)addHandleToAddressBook:(id)arg1;
+ (id)startChatWithPeople:(id)arg1;
+ (id)sendMessageToPeople:(id)arg1;
+ (_Bool)sendMessageToIMHandle:(id)arg1;
+ (id)_sendMessageToPeople:(id)arg1 style:(int)arg2;
+ (BOOL)validateMenuItem:(id)arg1 forPeople:(id)arg2;
+ (BOOL)allPeopleHaveEMailAddresses:(id)arg1;
+ (id)commonServicesForPeople:(id)arg1 requireOnline:(BOOL)arg2;
+ (id)servicesForIMHandle:(id)arg1 requireOnline:(BOOL)arg2;
+ (BOOL)buddyExistInSelection:(id)arg1;
+ (BOOL)allPeopleCanChat:(id)arg1;
+ (BOOL)allPeopleCanReceiveFiles:(id)arg1;
+ (BOOL)allPeople:(id)arg1 haveCapability:(unsigned long long)arg2;
+ (BOOL)allPeopleCanReceiveIMs:(id)arg1;
+ (BOOL)_allPeople:(id)arg1 haveCapability:(unsigned long long)arg2 skipUnknown:(BOOL)arg3 rejectOffline:(BOOL)arg4;
+ (id)bestIMHandlesForPeople:(id)arg1;
+ (id)bestIMHandlesForPeople:(id)arg1 requireOnline:(BOOL)arg2;
+ (id)bestIMHandlesForPeople:(id)arg1 commonServices:(id)arg2 requireOnline:(BOOL)arg3;
+ (void)_postOfflineWarningForPeople:(id)arg1;
+ (void)_postNoCommonServicesForPeople:(id)arg1;

@end

