//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, NSView, iMessagePreferences;

@interface Prefs_Accounts : NSViewController <NSTableViewDataSource, NSTableViewDelegate>
{
    iMessagePreferences *_iMessagePreferencesViewController;
    NSView *_accountSettingsContainer;
    NSLayoutConstraint *_accountSettingsContainerMinimumWidthConstraint;
}

@property(retain) NSLayoutConstraint *accountSettingsContainerMinimumWidthConstraint; // @synthesize accountSettingsContainerMinimumWidthConstraint=_accountSettingsContainerMinimumWidthConstraint;
@property(retain) NSView *accountSettingsContainer; // @synthesize accountSettingsContainer=_accountSettingsContainer;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)showHelp:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

