//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "IMCloudKitEventHandler-Protocol.h"
#import "TKTonePickerViewControllerDelegate-Protocol.h"

@class IMCloudKitSyncState, NSButton, NSMenuItem, NSPopUpButton, NSSlider, NSString, NSView, SOAdjustableLayoutView, TKTonePickerViewController;

@interface Prefs_General : NSViewController <TKTonePickerViewControllerDelegate, IMCloudKitEventHandler>
{
    NSPopUpButton *_placeholderSoundsPopUpButton;
    NSButton *_saveConversationsOnClosingButton;
    NSButton *_notifyAboutMessagesFromUnknownContactsCheckbox;
    NSButton *_addressMeInGroupChatButton;
    NSButton *_playSoundsCheckbox;
    SOAdjustableLayoutView *_soundPopupContainerView;
    TKTonePickerViewController *_tonePickerController;
    NSPopUpButton *_downloadPathPopUpButton;
    NSPopUpButton *_keepMessagesPopUp;
    NSPopUpButton *_customFontMenu;
    NSView *_textSizeSliderContainerView;
    NSSlider *_textSizeSlider;
    NSMenuItem *_customFontMenuItem;
    NSMenuItem *_lastCustomFontMenuItem;
    NSMenuItem *_lastCustomFontMenuItemSeparator;
    IMCloudKitSyncState *_lastSyncState;
}

+ (id)defaultFont;
@property(retain) IMCloudKitSyncState *lastSyncState; // @synthesize lastSyncState=_lastSyncState;
@property(retain) NSMenuItem *lastCustomFontMenuItemSeparator; // @synthesize lastCustomFontMenuItemSeparator=_lastCustomFontMenuItemSeparator;
@property(retain) NSMenuItem *lastCustomFontMenuItem; // @synthesize lastCustomFontMenuItem=_lastCustomFontMenuItem;
@property(retain) NSMenuItem *customFontMenuItem; // @synthesize customFontMenuItem=_customFontMenuItem;
@property(retain) NSSlider *textSizeSlider; // @synthesize textSizeSlider=_textSizeSlider;
@property __weak NSView *textSizeSliderContainerView; // @synthesize textSizeSliderContainerView=_textSizeSliderContainerView;
@property(retain) NSPopUpButton *customFontMenu; // @synthesize customFontMenu=_customFontMenu;
@property(retain) NSPopUpButton *keepMessagesPopUp; // @synthesize keepMessagesPopUp=_keepMessagesPopUp;
@property(retain) NSPopUpButton *downloadPathPopUpButton; // @synthesize downloadPathPopUpButton=_downloadPathPopUpButton;
@property(retain) TKTonePickerViewController *tonePickerController; // @synthesize tonePickerController=_tonePickerController;
@property(retain) SOAdjustableLayoutView *soundPopupContainerView; // @synthesize soundPopupContainerView=_soundPopupContainerView;
@property(retain) NSButton *playSoundsCheckbox; // @synthesize playSoundsCheckbox=_playSoundsCheckbox;
@property(retain) NSButton *addressMeInGroupChatButton; // @synthesize addressMeInGroupChatButton=_addressMeInGroupChatButton;
@property __weak NSButton *notifyAboutMessagesFromUnknownContactsCheckbox; // @synthesize notifyAboutMessagesFromUnknownContactsCheckbox=_notifyAboutMessagesFromUnknownContactsCheckbox;
@property(retain) NSButton *saveConversationsOnClosingButton; // @synthesize saveConversationsOnClosingButton=_saveConversationsOnClosingButton;
- (void).cxx_destruct;
- (void)updateSaveConversationOnClosingButtonState;
- (void)cloudKitEventNotificationManager:(id)arg1 syncStateDidChange:(id)arg2;
- (void)tonePickerViewController:(id)arg1 selectedToneWithIdentifier:(id)arg2;
- (void)_showTextSlider:(BOOL)arg1;
- (void)_updateLastCustomFontMenuItem;
- (void)_selectLastCustomFont;
- (void)_setCustomFont:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)chooseAFont:(id)arg1;
- (void)fontChanged:(id)arg1;
- (void)changeTextSize:(id)arg1;
- (void)setTextSize:(long long)arg1;
- (void)setKeepMessagesMode:(long long)arg1;
- (id)valueForKeepMessageMode:(long long)arg1;
- (long long)keepMessageModeForValue:(long long)arg1;
- (void)setSavedKeepForeverPopUpSelectionAndShouldUpdateKeepMessagesMode:(BOOL)arg1;
- (void)setSavedKeepForeverPopUpSelection;
- (void)setUpKeepMessagesPopUp;
- (void)_warnAboutDeletingMessagesForSelectedListItem:(long long)arg1;
- (void)keepMessagesSelected:(id)arg1;
- (void)playSoundsToggled:(id)arg1;
- (void)changeSaveConversations:(id)arg1;
- (void)showHelp:(id)arg1;
- (void)_setupDownloadPathMenu;
- (void)changeDownloadPath:(id)arg1;
- (void)addressMeInGroupChatChanged:(id)arg1;
- (void)toggleNotifyAboutMessagesFromUnknownContacts:(id)arg1;
- (void)initializeFromDefaults;
- (void)_updateAccessibilityFontControl:(id)arg1;
- (void)_updateTextSizeControl:(id)arg1;
- (void)viewWillAppear;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

