//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "AKInlineSignInViewControllerDelegate-Protocol.h"

@class AKShortInlineSignInViewController, NSLayoutConstraint, NSString, NSTextField, NSView;

@interface SignInViewController : NSViewController <AKInlineSignInViewControllerDelegate>
{
    NSTextField *_iMessageTitleLabel;
    NSTextField *_signInBlurb;
    NSView *_authenticationView;
    NSLayoutConstraint *_authenticationViewHeightConsttraint;
    AKShortInlineSignInViewController *_akSignInViewController;
}

@property(retain) AKShortInlineSignInViewController *akSignInViewController; // @synthesize akSignInViewController=_akSignInViewController;
@property(retain) NSLayoutConstraint *authenticationViewHeightConsttraint; // @synthesize authenticationViewHeightConsttraint=_authenticationViewHeightConsttraint;
@property __weak NSView *authenticationView; // @synthesize authenticationView=_authenticationView;
@property(retain) NSTextField *signInBlurb; // @synthesize signInBlurb=_signInBlurb;
@property(retain) NSTextField *iMessageTitleLabel; // @synthesize iMessageTitleLabel=_iMessageTitleLabel;
- (void).cxx_destruct;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (BOOL)signInViewController:(id)arg1 shouldContinueWithAuthenticationResults:(id)arg2 error:(id)arg3 forContext:(id)arg4;
- (void)signInViewController:(id)arg1 didAuthenticateWithResults:(id)arg2 error:(id)arg3;
- (void)notNow;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

