//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSString;

@interface _DPBitValueRecordMO : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(nonatomic) short clearBitValue; // @dynamic clearBitValue;
@property(nonatomic) double creationDate; // @dynamic creationDate;
@property(copy, nonatomic) NSString *key; // @dynamic key;
@property(copy, nonatomic) NSString *privateBitValueStr; // @dynamic privateBitValueStr;
@property(nonatomic) long long reportVersion; // @dynamic reportVersion;
@property(nonatomic) BOOL submitted; // @dynamic submitted;

@end

