//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <DifferentialPrivacy/_DPCMSWordMO.h>

@interface _DPHCMSWordMO : _DPCMSWordMO
{
}

+ (id)fetchRequest;

// Remaining properties
@property(nonatomic) int fragmentBitIndex; // @dynamic fragmentBitIndex;
@property(nonatomic) int sequenceBitIndex; // @dynamic sequenceBitIndex;

@end

