//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSUUID.h>

@interface NSUUID (MSPAdditions)
+ (id)_maps_UUIDWithUUIDString:(id)arg1;
+ (id)_maps_zeroUUID;
- (long long)_maps_compare:(id)arg1;
@end

