//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <MediaRemote/NSObject-Protocol.h>

@protocol MRAVDistantRoutingDiscoveryServiceProtocol <NSObject>
- (void)getAvailableOutputDevicesWithCompletion:(void (^)(NSArray *, NSError *))arg1;
- (void)getAvailableEndpointsWithCompletion:(void (^)(NSArray *, NSError *))arg1;
- (void)setDiscoveryMode:(unsigned int)arg1 withCompletion:(void (^)(NSError *))arg2;
- (void)getDiscoveryModeWithCompletion:(void (^)(unsigned int, NSError *))arg1;
- (void)getDevicePresenceDetectedWithCompletion:(void (^)(BOOL, NSError *))arg1;
@end

