//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MRAVOutputDeviceSourceInfo : NSObject
{
    BOOL _multipleBuiltInDevices;
    NSString *_routingContextUID;
}

@property(readonly, nonatomic) BOOL multipleBuiltInDevices; // @synthesize multipleBuiltInDevices=_multipleBuiltInDevices;
@property(readonly, nonatomic) NSString *routingContextUID; // @synthesize routingContextUID=_routingContextUID;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)initWithRoutingContextUID:(id)arg1 multipleBuiltInDevices:(BOOL)arg2;

@end

