//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKitCore/NSObject-Protocol.h>

@class UIView;
@protocol UICoordinateSpace, _UIClickInteractionDriverDelegate;

@protocol _UIClickInteractionDriving <NSObject>
@property(nonatomic) double allowableMovement;
@property(nonatomic) __weak UIView *view;
@property(nonatomic) __weak id <_UIClickInteractionDriverDelegate> delegate;
- (void)cancelInteraction;
- (struct CGPoint)locationInCoordinateSpace:(id <UICoordinateSpace>)arg1;
@end

