//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSRunLoop, NSTimer;

__attribute__((visibility("hidden")))
@interface _UIDisplayLink : NSObject
{
    NSTimer *_timer;
    double _vblSeedTime;
    unsigned int _displayId;
    struct StdFBShmem_t *_displaySharedMemory;
    unsigned long long _displaySharedMemorySize;
    unsigned int _displayServiceConnection;
    BOOL _paused;
    double _timestamp;
    double _duration;
    double _targetTimestamp;
    long long _preferredFramesPerSecond;
    id _target;
    SEL _selector;
    NSRunLoop *_targetRunloop;
    NSMutableSet *_targetRunloopModes;
}

+ (id)displayLinkWithTarget:(id)arg1 selector:(SEL)arg2;
@property(retain, nonatomic) NSMutableSet *targetRunloopModes; // @synthesize targetRunloopModes=_targetRunloopModes;
@property(retain, nonatomic) NSRunLoop *targetRunloop; // @synthesize targetRunloop=_targetRunloop;
@property(nonatomic) SEL selector; // @synthesize selector=_selector;
@property(retain, nonatomic) id target; // @synthesize target=_target;
@property(nonatomic) long long preferredFramesPerSecond; // @synthesize preferredFramesPerSecond=_preferredFramesPerSecond;
@property(nonatomic, getter=isPaused) BOOL paused; // @synthesize paused=_paused;
@property(nonatomic) double targetTimestamp; // @synthesize targetTimestamp=_targetTimestamp;
@property(readonly, nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)invalidate;
- (double)_nextVsyncTime;
- (void)dealloc;
- (void)_connectServiceForDisplayId:(unsigned int)arg1;
- (id)init;
@property(readonly, nonatomic) double maximumRefreshRate;
- (void)_signalTargetForTargetTimestamp:(double)arg1 currentTime:(double)arg2;
- (void)_stopTimer;
- (void)_beginTimerWithInitialDelay:(double)arg1;
- (void)_performCallbackWithTargetTimestamp:(double)arg1 delay:(double)arg2;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)addToRunLoop:(id)arg1 forMode:(id)arg2;

@end

