//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKitCore/NSObject-Protocol.h>

@class NSString;
@protocol UICoordinateSpace;

@protocol _UIGestureStudyParticipating <NSObject>
@property(readonly, nonatomic) double movement;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) NSString *eventName;
- (struct CGPoint)locationInCoordinateSpace:(id <UICoordinateSpace>)arg1;
@end

