//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _UIMenuBarController : NSObject
{
    BOOL _menuChangeShouldRebuildMenu;
    NSArray *__objectsForSharing;
    CDUnknownBlockType _contextMenuDidClose;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL menuChangeShouldRebuildMenu; // @synthesize menuChangeShouldRebuildMenu=_menuChangeShouldRebuildMenu;
@property(copy, nonatomic) CDUnknownBlockType contextMenuDidClose; // @synthesize contextMenuDidClose=_contextMenuDidClose;
@property(copy, nonatomic, setter=_setObjectsForSharing:) NSArray *_objectsForSharing; // @synthesize _objectsForSharing=__objectsForSharing;
- (void).cxx_destruct;
- (id)_newSpeechMenuItem;
- (void)_notifyContextMenuClosed;
- (void)_makeContextMenuMoreMacLike:(id)arg1 isTextContextMenu:(BOOL)arg2 textIsEditable:(BOOL)arg3 hasObjectsToShare:(BOOL)arg4;
- (void)showContextMenu:(id)arg1 atLocation:(struct CGPoint)arg2 objectsForServicesAndSharing:(id)arg3 notifyingWhenClosed:(CDUnknownBlockType)arg4;
- (BOOL)shouldDeleteStandardItem:(id)arg1;
- (void)addCustomItemsToMenu:(id)arg1 afterItem:(id)arg2 toItemArray:(id)arg3;
- (void)addCustomMenusAfterMenu:(id)arg1 toItemArray:(id)arg2;
- (void)menuChanged:(id)arg1;
- (void)buildMenuBar;
- (id)init;

@end

