//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <UIKitCore/UIInteractionContext-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIPercentDrivenInteractionEffectChangeContext : NSObject <UIInteractionContext>
{
    BOOL _ended;
    double _progress;
}

@property(nonatomic) BOOL ended; // @synthesize ended=_ended;
@property(nonatomic) double progress; // @synthesize progress=_progress;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

