//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKitCore/UIPreviewInteractionDelegate-Protocol.h>

@class UIPreviewInteraction, UIView, UIViewController, _UIPreviewInteractionHighlighter, _UIPreviewInteractionViewControllerPresentation;

@protocol UIPreviewInteractionDelegatePrivate <UIPreviewInteractionDelegate>

@optional
- (UIView *)_previewInteractionOverrideViewForCommitPhase:(UIPreviewInteraction *)arg1;
- (BOOL)_previewInteractionShouldAutomaticallyTransitionToPreviewAfterDelay:(UIPreviewInteraction *)arg1;
- (BOOL)_previewInteractionShouldFinishTransitionToPreview:(UIPreviewInteraction *)arg1;
- (_UIPreviewInteractionViewControllerPresentation *)_previewInteraction:(UIPreviewInteraction *)arg1 viewControllerPresentationForPresentingViewController:(UIViewController *)arg2;
- (_UIPreviewInteractionHighlighter *)_previewInteractionHighlighterForPreviewTransition:(UIPreviewInteraction *)arg1;
@end

