//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ADMIndefiniteGracePeriodHandler : NSObject
{
}

+ (void)handleEnablingAutoLoginForUser:(id)arg1 window:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)messageStringForIsComputerUnlockEnabled:(BOOL)arg1 isApplePayEnabled:(BOOL)arg2 isStorePurchaseEnabled:(BOOL)arg3;
+ (id)titleStringForIsComputerUnlockEnabled:(BOOL)arg1 isApplePayEnabled:(BOOL)arg2 isStorePurchaseEnabled:(BOOL)arg3;

@end

