//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface HIDDisplayInterface : NSObject
{
    struct __IOHIDManager *_manager;
    struct __IOHIDDevice *_deviceRef;
    NSString *_containerID;
}

@property(readonly) NSString *containerID; // @synthesize containerID=_containerID;
- (void).cxx_destruct;
@property(readonly) NSArray *capabilities;
- (BOOL)extract:(id)arg1 error:(id *)arg2;
- (BOOL)commit:(id)arg1 error:(id *)arg2;
- (void)setDevice:(struct __IOHIDDevice *)arg1;
- (struct __IOHIDDevice *)device;
- (id)getDeviceElements:(id)arg1;
- (id)initWithMatching:(id)arg1;
- (id)getHIDDevices;
- (id)getHIDDevicesForMatching:(id)arg1;
- (BOOL)hasMatchingContainerID:(struct __IOHIDDevice *)arg1 containerID:(id)arg2;
- (void)dealloc;
- (id)initWithContainerID:(id)arg1;

@end

