//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSArray, _INPBCondition, _INPBDateTimeRange;

@protocol _INPBDateTimeRangeList <NSObject>
+ (Class)dateRangeType;
@property(readonly, nonatomic) unsigned long long dateRangesCount;
@property(copy, nonatomic) NSArray *dateRanges;
@property(readonly, nonatomic) BOOL hasCondition;
@property(retain, nonatomic) _INPBCondition *condition;
- (_INPBDateTimeRange *)dateRangeAtIndex:(unsigned long long)arg1;
- (void)addDateRange:(_INPBDateTimeRange *)arg1;
- (void)clearDateRanges;
@end

