//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@protocol _INPBLocalTime <NSObject>
@property(nonatomic) BOOL hasSecondOfMinute;
@property(nonatomic) long long secondOfMinute;
@property(nonatomic) BOOL hasMinuteOfHour;
@property(nonatomic) long long minuteOfHour;
@property(nonatomic) BOOL hasMillisOfSecond;
@property(nonatomic) long long millisOfSecond;
@property(nonatomic) BOOL hasHourOfDay;
@property(nonatomic) long long hourOfDay;
@end

