//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSData, NSString;

@protocol _INPBIntentResponsePayloadSuccess <NSObject>
@property(nonatomic) BOOL hasShouldOpenContainingApplication;
@property(nonatomic) BOOL shouldOpenContainingApplication;
@property(readonly, nonatomic) BOOL hasResponseTypeName;
@property(copy, nonatomic) NSString *responseTypeName;
@property(readonly, nonatomic) BOOL hasResponseMessageData;
@property(copy, nonatomic) NSData *responseMessageData;
@end

