//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSString, _INPBLocation;

@protocol _INPBStartPhotoPlaybackIntentResponse <NSObject>
@property(nonatomic) BOOL hasSearchResultsCount;
@property(nonatomic) int searchResultsCount;
@property(readonly, nonatomic) BOOL hasLocationCreated;
@property(retain, nonatomic) _INPBLocation *locationCreated;
@property(readonly, nonatomic) BOOL hasAlbumName;
@property(copy, nonatomic) NSString *albumName;
@end

