//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/JSExport-Protocol.h>
#import <Intents/NSObject-Protocol.h>

@class INRestaurant, INRestaurantGuest, INRestaurantOffer, NSDateComponents, NSString;

@protocol INBookRestaurantReservationIntentExport <NSObject, JSExport>
@property(copy) NSString *guestProvidedSpecialRequestText;
@property(copy) INRestaurantOffer *selectedOffer;
@property(copy) INRestaurantGuest *guest;
@property(copy) NSString *bookingIdentifier;
@property unsigned long long partySize;
@property(copy) NSDateComponents *bookingDateComponents;
@property(copy) INRestaurant *restaurant;
- (id)init;
@end

