//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/INIntentResolutionResult.h>

@interface INTaskListResolutionResult : INIntentResolutionResult
{
}

+ (id)confirmationRequiredWithTaskListToConfirm:(id)arg1;
+ (id)disambiguationWithTaskListsToDisambiguate:(id)arg1;
+ (id)successWithResolvedTaskList:(id)arg1;

@end

