//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSVTimer;
@protocol OS_dispatch_queue;

@interface MSVBlockGuard : NSObject
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    BOOL _disarmed;
    BOOL _didTimeout;
    MSVTimer *_timeoutTimer;
    CDUnknownBlockType _interruptionHandler;
}

- (void).cxx_destruct;
- (BOOL)disarm;
- (void)_interruptWithReason:(long long)arg1;
- (void)dealloc;
- (id)initWithTimeout:(double)arg1 interruptionHandler:(CDUnknownBlockType)arg2;
- (id)initWithTimeout:(double)arg1;
- (id)initWithDeallocHandler:(CDUnknownBlockType)arg1;
- (id)init;

@end

