//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSUUID.h>

@interface NSUUID (MSVBase64)
+ (id)uuidWithMSVBase64UUID:(id)arg1;
- (id)MSVBase64UUIDString;
- (id)initWithMSVBase64UUIDString:(id)arg1;
@end

