//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ADMAccountPasswordPolicy : NSObject
{
}

+ (id)updatePasswordPolicy:(long long)arg1 userName:(id)arg2 password:(id)arg3;
+ (id)policyDescriptionFor:(long long)arg1;

@end

