//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (TIMecabraEnvironment)
- (BOOL)TI_hasTrueSuffix:(id)arg1;
- (BOOL)TI_hasTruePrefix:(id)arg1;
- (id)longestCommonSubstring:(id)arg1 backwards:(BOOL)arg2;
- (unsigned short *)characters;
- (id)stringByRemovingPunctuationAndExplicitWhitespaces:(unsigned long long)arg1;
@end

