//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <TextInputCore/TILanguageModelOfflineLearningHandle.h>

@class TIWordSearch;

@interface TILanguageModelOfflineLearningHandleMecabra : TILanguageModelOfflineLearningHandle
{
    TIWordSearch *_wordSearch;
}

@property(retain, nonatomic) TIWordSearch *wordSearch; // @synthesize wordSearch=_wordSearch;
- (void).cxx_destruct;
- (void)didFinishLearning;
- (void)adaptToParagraph:(id)arg1 timeStamp:(double)arg2 adaptationType:(int)arg3;
- (void)load;
- (void)updateAdaptationContext:(id)arg1;

@end

