//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC7Console14ViewController.h"

@interface _TtC7Console25PlaceholderViewController : _TtC7Console14ViewController
{
    // Error parsing type: , name: textField
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

