//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "_TtC7Console24SourceListViewController.h"

@interface _TtC7Console21SourcesViewController : _TtC7Console24SourceListViewController
{
    // Error parsing type: , name: sources
    // Error parsing type: , name: devicesObserver
    // Error parsing type: , name: directoryObservers
    // Error parsing type: , name: viewWasRenderedOnce
    // Error parsing type: , name: persistentViewControllers
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)stateActionButtonDidClick:(id)arg1;
- (void)shouldSelectDeviceUDID:(id)arg1;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

