//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@protocol NPUNowPlayingControlStripButtonDelegate;

@interface NPUNowPlayingControlStripButton : NSButton
{
    unsigned long long _currentTapCount;
    id <NPUNowPlayingControlStripButtonDelegate> _delegate;
}

@property(nonatomic) __weak id <NPUNowPlayingControlStripButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_sendDoubleTapEvent:(id)arg1;
- (void)_sendSingleTapEvent:(id)arg1;
- (void)touchesEndedWithEvent:(id)arg1;

@end

