//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

@interface AMCPUUsageCollectionViewItem : NSCollectionViewItem
{
    long long _maxLevel;
    long long _cpuLevel;
}

@property(nonatomic) long long cpuLevel; // @synthesize cpuLevel=_cpuLevel;
@property(nonatomic) long long maxLevel; // @synthesize maxLevel=_maxLevel;
- (void)viewDidLoad;

@end

