//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class CacheGraphView, NSMutableArray, NSObject, NSPopUpButton, NSScrollView, NSTableView, NSTextField, SMCacheMetricsReader;
@protocol OS_dispatch_semaphore;

@interface SMCacheController : NSViewController
{
    NSObject<OS_dispatch_semaphore> *cacheGraphSemaphore;
    NSScrollView *_listView;
    NSTableView *_cacheTableView;
    NSPopUpButton *_cacheGraphPopUp;
    NSMutableArray *_summarizedCacheMetrics;
    SMCacheMetricsReader *_metricsReader;
    long long _graphPopUpTag;
    CacheGraphView *_cachePressureGraph;
    NSTextField *_cachePressureLabel;
    NSTextField *_totalDataServedLabel;
    NSTextField *_servedFromCacheLabel;
    CacheGraphView *_dataServedGraph;
}

@property __weak CacheGraphView *dataServedGraph; // @synthesize dataServedGraph=_dataServedGraph;
@property __weak NSTextField *servedFromCacheLabel; // @synthesize servedFromCacheLabel=_servedFromCacheLabel;
@property __weak NSTextField *totalDataServedLabel; // @synthesize totalDataServedLabel=_totalDataServedLabel;
@property __weak NSTextField *cachePressureLabel; // @synthesize cachePressureLabel=_cachePressureLabel;
@property __weak CacheGraphView *cachePressureGraph; // @synthesize cachePressureGraph=_cachePressureGraph;
@property long long graphPopUpTag; // @synthesize graphPopUpTag=_graphPopUpTag;
@property(retain) SMCacheMetricsReader *metricsReader; // @synthesize metricsReader=_metricsReader;
@property(retain) NSMutableArray *summarizedCacheMetrics; // @synthesize summarizedCacheMetrics=_summarizedCacheMetrics;
@property(retain) NSPopUpButton *cacheGraphPopUp; // @synthesize cacheGraphPopUp=_cacheGraphPopUp;
@property(retain) NSTableView *cacheTableView; // @synthesize cacheTableView=_cacheTableView;
@property(retain) NSScrollView *listView; // @synthesize listView=_listView;
- (void).cxx_destruct;
- (void)graphPopUpChanged:(id)arg1;
@property double interval;
- (void)stop;
- (void)start;
- (void)refreshGraphsAndLabels;
- (void)viewDidLoad;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

