//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol OS_dispatch_queue;

@interface SMGPUMonitor : NSObject
{
    NSArray *_GPUs;
    id _metalObserver;
    CDUnknownBlockType _changeNotificationHandler;
    NSObject<OS_dispatch_queue> *_notificationQueue;
}

@property(retain) NSObject<OS_dispatch_queue> *notificationQueue; // @synthesize notificationQueue=_notificationQueue;
@property(copy) CDUnknownBlockType changeNotificationHandler; // @synthesize changeNotificationHandler=_changeNotificationHandler;
@property(retain) id metalObserver; // @synthesize metalObserver=_metalObserver;
@property(retain) NSArray *GPUs; // @synthesize GPUs=_GPUs;
- (void).cxx_destruct;
- (void)updateGPUs;
- (void)dealloc;
- (id)initWithChangeNotificationHandler:(CDUnknownBlockType)arg1;

@end

