//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BKLocalization : NSObject
{
}

+ (id)getStringFromBundleLocalizationTable:(id)arg1 withBundle:(id)arg2 inLocalization:(id)arg3 fromTable:(id)arg4;
+ (id)getLocalizedString:(id)arg1 withBundle:(id)arg2 defaultValue:(id)arg3;
+ (BOOL)isiPad;
+ (id)getLocalizedString:(id)arg1;

@end

