//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface _KSControlFileController : NSObject
{
    NSURL *_url;
}

- (void).cxx_destruct;
- (id)description;
- (void)setContents:(id)arg1;
- (id)contents;
- (void)reset;
- (BOOL)checkIfExists;
- (id)initWithName:(id)arg1 inDirectory:(id)arg2;

@end

