//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CNArchiver : NSObject
{
}

+ (id)decodeObjectOfClass:(Class)arg1 associatedClasses:(id)arg2 data:(id)arg3 error:(id *)arg4;
+ (id)decodeObjectOfClass:(Class)arg1 data:(id)arg2 error:(id *)arg3;
+ (id)encodeObject:(id)arg1 error:(id *)arg2;
+ (id)os_log;

@end

