//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ContactsFoundation/NSObject-Protocol.h>

@protocol NSCopying;

@protocol CNCacheBoundingStrategy <NSObject>
- (void)willAccessKey:(id <NSCopying>)arg1;
- (BOOL)shouldEvictKey:(id <NSCopying>)arg1;
- (void)willUpdateCacheBy:(unsigned long long)arg1 forKey:(id <NSCopying>)arg2 keysToEvict:(id *)arg3;
@end

