//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <WebContentAnalysis/WFTreeXMLDocumentStripper.h>

@interface WFTreeHTMLStripper : WFTreeXMLDocumentStripper
{
    struct _xmlDoc *_document;
}

+ (id)treeStripperWithString:(id)arg1;
+ (id)treeStripperWithData:(id)arg1;
- (void)dealloc;
- (id)initWithString:(id)arg1;
- (id)initWithData:(id)arg1;

@end

