//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "SettableIntrinsicSizeView.h"

@class NSArray, RCRecordingFullCompactControl, RCToolBarController, RCTouchInsetsButton, UILabel, UILongPressGestureRecognizer;
@protocol RCControlsActionDelegate;

@interface RCEditingToolbar : SettableIntrinsicSizeView
{
    BOOL _canUndo;
    BOOL _canCancel;
    BOOL _canSave;
    BOOL _showEditingModes;
    long long _displayMode;
    long long _activityMode;
    id <RCControlsActionDelegate> _controlsActionDelegate;
    RCToolBarController *_toolBarController;
    RCTouchInsetsButton *_trimButton;
    RCTouchInsetsButton *_rightSideButton;
    RCTouchInsetsButton *_leftSideButton;
    UILabel *_titleLabel;
    RCRecordingFullCompactControl *_fullCompactControl;
    NSArray *_buttonsArray;
    UILongPressGestureRecognizer *_longPressGestureForAXHUDViewGR;
}

@property BOOL showEditingModes; // @synthesize showEditingModes=_showEditingModes;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureForAXHUDViewGR; // @synthesize longPressGestureForAXHUDViewGR=_longPressGestureForAXHUDViewGR;
@property(retain, nonatomic) NSArray *buttonsArray; // @synthesize buttonsArray=_buttonsArray;
@property(retain, nonatomic) RCRecordingFullCompactControl *fullCompactControl; // @synthesize fullCompactControl=_fullCompactControl;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) RCTouchInsetsButton *leftSideButton; // @synthesize leftSideButton=_leftSideButton;
@property(retain, nonatomic) RCTouchInsetsButton *rightSideButton; // @synthesize rightSideButton=_rightSideButton;
@property(retain, nonatomic) RCTouchInsetsButton *trimButton; // @synthesize trimButton=_trimButton;
@property(nonatomic) __weak RCToolBarController *toolBarController; // @synthesize toolBarController=_toolBarController;
@property(nonatomic) __weak id <RCControlsActionDelegate> controlsActionDelegate; // @synthesize controlsActionDelegate=_controlsActionDelegate;
@property(nonatomic) BOOL canSave; // @synthesize canSave=_canSave;
@property(nonatomic) BOOL canCancel; // @synthesize canCancel=_canCancel;
@property(nonatomic) BOOL canUndo; // @synthesize canUndo=_canUndo;
@property(nonatomic) long long activityMode; // @synthesize activityMode=_activityMode;
@property(nonatomic) long long displayMode; // @synthesize displayMode=_displayMode;
- (void).cxx_destruct;
- (BOOL)_isActionEnabled:(long long)arg1;
- (void)didChangePreferredContentSize;
- (id)buttonAtPoint:(struct CGPoint)arg1;
- (void)handleAccessibilityLongPress:(id)arg1;
- (void)setupAXHUDLongPressGestureIfNecessary;
- (void)_handleFullCompactControl;
- (void)_handleAction:(id)arg1;
- (void)_handleTrim;
- (void)_commonInit;
- (void)_classSpecificInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)_updateControlsToHidden:(BOOL)arg1 enabled:(BOOL)arg2 rightSideButtonVisible:(BOOL)arg3 leftSideButtonVisible:(BOOL)arg4 dimmedMode:(BOOL)arg5;
- (void)_setupForSaveTitle;
- (void)_setupForDoneTitle;
- (void)_setupForCancelTitle;
- (void)_setupForUndoTitle;
- (void)_syncViewsToState;
- (void)_updateFullCompactControl;

@end

