//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface RCPassthroughViewsSpec : NSObject
{
    BOOL _includeTopLevelView;
    UIView *_topLevelView;
}

+ (id)passthroughViewsSpecWithTopLevelView:(id)arg1 includeTopLevelView:(BOOL)arg2;
@property(nonatomic) BOOL includeTopLevelView; // @synthesize includeTopLevelView=_includeTopLevelView;
@property(nonatomic) __weak UIView *topLevelView; // @synthesize topLevelView=_topLevelView;
- (void).cxx_destruct;

@end

