//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class NSArray, NSIndexPath, RCRecordingDisplayModel;

@protocol RCRecordingTableViewDataCoordinatorDelegate
- (void)contentChangesComplete;
- (void)didProcessUpdatesWithRemainingItemCount:(unsigned long long)arg1;
- (void)moveRowAtIndexPath:(NSIndexPath *)arg1 toIndexPath:(NSIndexPath *)arg2;
- (void)deleteRowsAtIndexPaths:(NSArray *)arg1;
- (void)reloadRowAtIndexPath:(NSIndexPath *)arg1 usingDisplayModel:(RCRecordingDisplayModel *)arg2;
- (void)insertRowsAtIndexPaths:(NSArray *)arg1;
- (void)prepareForChangingContent;
@end

