//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "RCRecentlyDeletedHandler-Protocol.h"
#import "RCRecordingTableViewDataCoordinatorDelegate-Protocol.h"
#import "RCTableViewCellDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchControllerDelegate-Protocol.h"
#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDragDelegate-Protocol.h"

@class NSIndexPath, NSString, RCRecentlyDeletedRecordingTableViewController, RCRecentlyDeletedSummaryCell, RCRecordingTableViewControllerDataCoordinator, UISearchController;
@protocol RCLibraryActionHandler, RCRecentlyDeletedHandler, RCRecording;

@interface RCRecordingTableViewController : UITableViewController <RCTableViewCellDelegate, RCRecentlyDeletedHandler, RCRecordingTableViewDataCoordinatorDelegate, UISearchBarDelegate, UISearchControllerDelegate, UISearchResultsUpdating, UITableViewDragDelegate>
{
    BOOL _didDeleteRows;
    BOOL _didInsertRows;
    BOOL _needToSelectFirstRow;
    BOOL _isShowingRecentlyDeleted;
    BOOL _isSearching;
    id <RCLibraryActionHandler> _libraryActionHandler;
    id <RCRecentlyDeletedHandler> _recentlyDeletedHandler;
    UISearchController *_searchController;
    RCRecordingTableViewControllerDataCoordinator *_recordingsDataCoordinator;
    CDUnknownBlockType _swipeToEraseCompletionHandler;
    NSString *_normalRecordingsSearchStringForRestore;
    RCRecentlyDeletedRecordingTableViewController *_recentlyDeletedTableViewController;
    RCRecentlyDeletedSummaryCell *_recentlyDeletedSummaryCell;
    unsigned long long _countOfRecentlyDeleted;
    unsigned long long _showsRecentlyDeleted;
    NSString *_uuidOfNewestRecording;
    NSString *_uuidOfSelectedRow;
    NSIndexPath *_indexPathOfRowSwipedForEditing;
}

@property(retain, nonatomic) NSIndexPath *indexPathOfRowSwipedForEditing; // @synthesize indexPathOfRowSwipedForEditing=_indexPathOfRowSwipedForEditing;
@property(retain, nonatomic) NSString *uuidOfSelectedRow; // @synthesize uuidOfSelectedRow=_uuidOfSelectedRow;
@property(copy, nonatomic) NSString *uuidOfNewestRecording; // @synthesize uuidOfNewestRecording=_uuidOfNewestRecording;
@property(nonatomic) unsigned long long showsRecentlyDeleted; // @synthesize showsRecentlyDeleted=_showsRecentlyDeleted;
@property(nonatomic) unsigned long long countOfRecentlyDeleted; // @synthesize countOfRecentlyDeleted=_countOfRecentlyDeleted;
@property(nonatomic) __weak RCRecentlyDeletedSummaryCell *recentlyDeletedSummaryCell; // @synthesize recentlyDeletedSummaryCell=_recentlyDeletedSummaryCell;
@property(retain, nonatomic) RCRecentlyDeletedRecordingTableViewController *recentlyDeletedTableViewController; // @synthesize recentlyDeletedTableViewController=_recentlyDeletedTableViewController;
@property(copy, nonatomic) NSString *normalRecordingsSearchStringForRestore; // @synthesize normalRecordingsSearchStringForRestore=_normalRecordingsSearchStringForRestore;
@property(nonatomic) BOOL isSearching; // @synthesize isSearching=_isSearching;
@property(copy) CDUnknownBlockType swipeToEraseCompletionHandler; // @synthesize swipeToEraseCompletionHandler=_swipeToEraseCompletionHandler;
@property(nonatomic) BOOL isShowingRecentlyDeleted; // @synthesize isShowingRecentlyDeleted=_isShowingRecentlyDeleted;
@property(retain, nonatomic) RCRecordingTableViewControllerDataCoordinator *recordingsDataCoordinator; // @synthesize recordingsDataCoordinator=_recordingsDataCoordinator;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) __weak id <RCRecentlyDeletedHandler> recentlyDeletedHandler; // @synthesize recentlyDeletedHandler=_recentlyDeletedHandler;
@property(nonatomic) __weak id <RCLibraryActionHandler> libraryActionHandler; // @synthesize libraryActionHandler=_libraryActionHandler;
- (void).cxx_destruct;
- (void)editSelectedRowTitle;
- (BOOL)_isRecentlyDeletedSummaryCellAtIndexPath:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)playCurrentSelection:(id)arg1;
- (void)jumpSelectionBackward:(id)arg1;
- (void)jumpSelectionForward:(id)arg1;
- (void)doDeleteAction;
- (void)delete:(id)arg1;
- (void)deleteCurrentSelection:(id)arg1;
- (void)moveSelectionDown:(id)arg1;
- (void)moveSelectionUp:(id)arg1;
- (id)keyCommands;
- (BOOL)canBecomeFirstResponder;
- (BOOL)accessibilityPerformEscape;
- (id)tableView:(id)arg1 itemsForBeginningDragSession:(id)arg2 atIndexPath:(id)arg3;
- (void)didUpdateToRecentlyDeletedCount:(unsigned long long)arg1;
- (void)_setSearchString:(id)arg1;
- (void)_updateSearchString:(id)arg1;
- (void)didDismissSearchController:(id)arg1;
- (void)willDismissSearchController:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)didPresentSearchController:(id)arg1;
- (void)_updateRecentlyDeletedInPreparationForSearch;
- (void)willPresentSearchController:(id)arg1;
- (id)_indexPathOfRecentlyDeletedSummaryCell;
- (void)_hideRecentlyDeletedSummaryCell;
- (void)_showRecentlyDeletedSummaryCell;
- (id)_uuidForRowAtIndexPath:(id)arg1;
- (BOOL)shouldIgnoreSelectionChangeForCellWithUUID:(id)arg1;
- (BOOL)recordingTitleHasBeenEditedForCellWithUUID:(id)arg1;
- (void)wasDeselectedForCellWithUUID:(id)arg1;
- (void)didSelectCellWithUUID:(id)arg1;
- (void)performRenameWithNewTitle:(id)arg1 forCellWithUUID:(id)arg2;
- (void)setCurrentTime:(double)arg1 forItemWithUUID:(id)arg2;
- (id)_displayModelAtIndex:(unsigned long long)arg1;
- (void)showIdleForItemWithUUID:(id)arg1;
- (void)showPlayingForItemWithUUID:(id)arg1;
- (void)performAction:(long long)arg1 atPosition:(double)arg2 forCellWithUUID:(id)arg3 source:(id)arg4;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_pushRecentlyDeletedController:(BOOL)arg1;
- (BOOL)_isIndexOfRecentlyDeletedSummaryAtIndex:(unsigned long long)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)_reuseIdentifierAtIndex:(unsigned long long)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)_configureCell:(id)arg1 atIndexPath:(id)arg2 usingDisplayModel:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (unsigned long long)_fetchedCountOfRecentlyDeleted;
- (BOOL)_isNormalMode;
- (long long)_expectedNumberOfRows;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)resetSwipedCell;
- (void)handleDeleteForUUID:(id)arg1;
- (void)_handleEditModeFooterAndNavigationItem;
- (void)_pushRecentlyDeletedIfNeeded:(BOOL)arg1;
- (void)selectItemWithUUID:(id)arg1;
- (BOOL)presentsRecordingWithUUID:(id)arg1;
- (void)scrollToTop;
- (void)deselectSelectedItem;
- (void)_selectItemAtIndexPath:(id)arg1 animated:(BOOL)arg2;
- (void)prepareForInitialPresentation;
- (void)_showOrHideEmptyLibrarySplashView;
- (void)contentChangesComplete;
- (void)deleteSelectedRows;
- (void)deleteUUIDs:(id)arg1 force:(BOOL)arg2 showInfo:(BOOL)arg3;
- (id)allUUIDs;
- (id)selectedUUIDs;
- (void)moveRowAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)deleteRowsAtIndexPaths:(id)arg1;
- (void)reloadRowAtIndexPath:(id)arg1 usingDisplayModel:(id)arg2;
- (void)insertRowsAtIndexPaths:(id)arg1;
- (void)prepareForChangingContent;
- (void)_logWhetherVisibleCellsHaveIntegrity;
- (void)_updateEditButtonStateForRecordingsCount:(unsigned long long)arg1;
- (void)didProcessUpdatesWithRemainingItemCount:(unsigned long long)arg1;
- (void)prepareForAdditionOfNewRecordingWithUUID:(id)arg1;
- (id)dataArray;
- (void)_updateUUIDOfSelectedRow;
- (void)handleUserCanceledDeletionSwipedCell;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_toggleEdit;
- (void)stylizeNavigationBar;
- (void)_classSpecificViewWillDisappear;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_classSpecificViewWillAppear;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)_classSpecificInit;
- (void)_commonInit;
- (id)initWithStyle:(long long)arg1;
@property(readonly, nonatomic) id <RCRecording> selectedRecording;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

