//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSUndoManager, RCRecordingCardView, UIView;

@interface RCRecordingCardViewController : UIViewController
{
    NSUndoManager *_undoManager;
}

- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (void)switchToBackgroundSnapshotForInterfaceOrientation:(long long)arg1;
- (void)setBackgroundSnapshotView:(id)arg1 forInterfaceOrientation:(long long)arg2;
@property(nonatomic) __weak UIView *hostedView;
@property(nonatomic) unsigned long long presentationOptions;
- (id)undoManager;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)canBecomeFirstResponder;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(retain, nonatomic) RCRecordingCardView *view; // @dynamic view;

@end

