//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _UIWindowToolbarButtonItem, _UIWindowToolbarController, _UIWindowToolbarLabelItem, _UIWindowToolbarShareItem;

@interface RCToolBarController : NSObject
{
    _UIWindowToolbarController *_windowToolbarController;
    _UIWindowToolbarLabelItem *_titleLabel;
    _UIWindowToolbarShareItem *_shareItem;
    _UIWindowToolbarButtonItem *_editItem;
    _UIWindowToolbarButtonItem *_trimItem;
    _UIWindowToolbarButtonItem *_recoverItem;
    _UIWindowToolbarButtonItem *_eraseItem;
}

@property(retain, nonatomic) _UIWindowToolbarButtonItem *eraseItem; // @synthesize eraseItem=_eraseItem;
@property(retain, nonatomic) _UIWindowToolbarButtonItem *recoverItem; // @synthesize recoverItem=_recoverItem;
@property(retain, nonatomic) _UIWindowToolbarButtonItem *trimItem; // @synthesize trimItem=_trimItem;
@property(retain, nonatomic) _UIWindowToolbarButtonItem *editItem; // @synthesize editItem=_editItem;
@property(retain, nonatomic) _UIWindowToolbarShareItem *shareItem; // @synthesize shareItem=_shareItem;
@property(retain, nonatomic) _UIWindowToolbarLabelItem *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) _UIWindowToolbarController *windowToolbarController; // @synthesize windowToolbarController=_windowToolbarController;
- (void).cxx_destruct;
- (void)setEraseTarget:(id)arg1 andAction:(SEL)arg2;
- (void)setEraseButtonEnabled:(BOOL)arg1;
- (void)setRecoverTarget:(id)arg1 andAction:(SEL)arg2;
- (void)setRecoverButtonEnabled:(BOOL)arg1;
- (void)setTrimTarget:(id)arg1 andAction:(SEL)arg2;
- (void)setTrimButtonEnabled:(BOOL)arg1;
- (void)setSharingActivityItems:(id)arg1;
- (void)setEditTarget:(id)arg1 andAction:(SEL)arg2;
- (void)setShareButtonEnabled:(BOOL)arg1;
- (void)setEditButtonEnabled:(BOOL)arg1;
- (void)setToolbarTitle:(id)arg1;
- (void)transitionToNothingSelected;
- (void)transitionToPlaybackMode:(BOOL)arg1;
- (void)transitionToEditMode;
- (id)items;
- (void)_updateToolBarButtons;
- (void)traitCollectionChanged:(id)arg1;
- (id)initWithWindowToolbarController:(id)arg1;

@end

