//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface RCWelcomeBulletView : UIView
{
    UIImageView *_icon;
    UILabel *_title;
    UILabel *_blurb;
}

@property(retain, nonatomic) UILabel *blurb; // @synthesize blurb=_blurb;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;

@end

