//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSLayoutConstraint, RCWelcomeBulletView, RCWelcomeButton, RCWelcomeTitleGroup, UIScrollView, UIView, UIVisualEffectView;

@interface RCWelcomeViewController : UIViewController
{
    UIView *_containerView;
    UIView *_scrollContentView;
    UIScrollView *_scrollView;
    RCWelcomeTitleGroup *_titleGroup;
    RCWelcomeBulletView *_bulletView1;
    RCWelcomeBulletView *_bulletView2;
    RCWelcomeBulletView *_bulletView3;
    RCWelcomeButton *_continueButton;
    UIVisualEffectView *_effectView;
    long long _animationState;
    NSLayoutConstraint *_titleTopMarginConstraint;
    NSLayoutConstraint *_titleMinTopMarginConstraint;
    NSLayoutConstraint *_titleIconSizeWidthConstraint;
    NSLayoutConstraint *_titleLabelTopMarginConstraint;
    NSLayoutConstraint *_bulletsTopMarginConstraint;
    NSLayoutConstraint *_bullet2TopMarginConstraint;
    NSLayoutConstraint *_bullet3TopMarginConstraint;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _completionAnimation;
    BOOL _didBreakLinesInTitle;
}

+ (id)backgroundColor;
+ (BOOL)needsShowing;
- (void).cxx_destruct;
- (double)_containerWidth;
- (void)_updateScrollViewContentSize;
- (void)_updateViews;
- (void)_updateConstraintsForHeight:(double)arg1;
- (void)_createContinueButton;
- (void)_createBulletsArea;
- (id)_createBulletViewWithTitle:(id)arg1 description:(id)arg2 icon:(id)arg3;
- (id)_createTitleLabel;
- (void)_createTitleGroup;
- (void)_createScrollableContent;
- (void)_createContainerView;
- (double)varPad:(double)arg1:(double)arg2:(double)arg3 phone:(double)arg4:(double)arg5:(double)arg6 containerHeight:(double)arg7;
- (double)varPad:(double)arg1:(double)arg2:(double)arg3 phone:(double)arg4:(double)arg5:(double)arg6;
- (void)handleContinueButton:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (BOOL)shouldAutorotate;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)initWithCompletionAnimation:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;

@end

