//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITimingCurveProvider-Protocol.h"

@class UICubicTimingParameters, UISpringTimingParameters;

@interface RCWelcomeAnimationTimings : NSObject <UITimingCurveProvider>
{
    UICubicTimingParameters *_cubicTimings;
    UISpringTimingParameters *_springTimings;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) UICubicTimingParameters *cubicTimingParameters;
@property(readonly, nonatomic) UISpringTimingParameters *springTimingParameters;
@property(readonly, nonatomic) long long timingCurveType;
- (id)_mediaTimingFunction;
- (id)initWithMass:(double)arg1 stiffness:(double)arg2 damping:(double)arg3;
- (id)initWithControlPoint1:(struct CGPoint)arg1 controlPoint2:(struct CGPoint)arg2;

@end

