//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCCaptureSessionObserver-Protocol.h"
#import "RCLocationsOfInterestDelegate-Protocol.h"
#import "RCMainViewControllerDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "UIApplicationDelegatePrivate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UISplitViewControllerDelegate-Protocol.h"

@class CKContainer, CLLocation, NSArray, NSString, RCAudioSessionRoutingAssertion, RCDetailContainerViewController, RCLocationsOfInterestManager, RCLockScreenViewController, RCMainViewController, RCSSavedRecordingService, RCSplitViewController, RCToolBarController, RCWaveformDataSource, UIAlertController, UINavigationController, UIWindow;

@interface RecorderAppDelegate : NSObject <UIApplicationDelegatePrivate, RCLocationsOfInterestDelegate, RCCaptureSessionObserver, RCMainViewControllerDelegate, UIGestureRecognizerDelegate, UINavigationControllerDelegate, UISplitViewControllerDelegate, UIApplicationDelegate>
{
    UIWindow *_window;
    UINavigationController *_mainNavigationController;
    UINavigationController *_detailNavigationController;
    RCMainViewController *_mainViewController;
    RCSplitViewController *_rootSplitViewController;
    UIAlertController *_fatalErrorAlertController;
    unsigned long long _backgroundTaskIdentifier;
    RCAudioSessionRoutingAssertion *_foregroundRouteAssertion;
    RCToolBarController *_toolBarController;
    RCSSavedRecordingService *_sharedService;
    CKContainer *_cloudContainer;
    int _cloudAccessChangedToken;
    RCLocationsOfInterestManager *_locationManager;
    int _removeAllRecordingsToken;
    int _resetDefaultsToken;
    BOOL _recordingActive;
    BOOL _isActive;
    BOOL _hasBecomeActiveOnce;
    BOOL _startCapturingRequestInFlight;
    BOOL _iCloudAvailable;
    BOOL _recordingCardPresented;
    BOOL _extendedLaunchTimeIsLogged;
    CLLocation *_currentLocation;
    NSArray *_locationsOfInterest;
    RCDetailContainerViewController *_playbackContainerViewController;
    RCLockScreenViewController *_virtualViewController;
    UINavigationController *_virtualNavigationController;
    UIWindow *_virtualWindow;
    double _duration;
}

+ (void)registerDefaults;
+ (void)initialize;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) UIWindow *virtualWindow; // @synthesize virtualWindow=_virtualWindow;
@property(retain, nonatomic) UINavigationController *virtualNavigationController; // @synthesize virtualNavigationController=_virtualNavigationController;
@property(retain, nonatomic) RCLockScreenViewController *virtualViewController; // @synthesize virtualViewController=_virtualViewController;
@property(retain, nonatomic) RCDetailContainerViewController *playbackContainerViewController; // @synthesize playbackContainerViewController=_playbackContainerViewController;
@property(retain, nonatomic) NSArray *locationsOfInterest; // @synthesize locationsOfInterest=_locationsOfInterest;
@property(retain, nonatomic) CLLocation *currentLocation; // @synthesize currentLocation=_currentLocation;
@property(nonatomic) BOOL extendedLaunchTimeIsLogged; // @synthesize extendedLaunchTimeIsLogged=_extendedLaunchTimeIsLogged;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (BOOL)accessibilityPerformMagicTap;
- (void)_failedToCreateDatabase:(id)arg1;
- (void)_handleDidFailCaptureSession:(id)arg1;
- (void)_handleDidEndCaptureSession:(id)arg1;
- (void)_handleDidResumeCaptureSession:(id)arg1;
- (void)_handleDidPauseCaptureSession:(id)arg1;
- (void)recordNewVoiceMemoFromIntent;
- (void)playbackMostRecentRecordingFromIntent;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)_startPlaybackQuickActionForRecordingWithUniqueID:(id)arg1;
- (void)_startNewRecordingQuickAction;
- (BOOL)_shouldPresentPlaybackQuickActions;
- (BOOL)_shouldPresentNewRecordingQuickAction;
- (void)_applicationDidFinishLaunching;
- (void)_checkAndReportUserLibrarySizeToCoreAnalytics;
- (void)_updateLastSuspendTime;
- (double)_lastSuspendTime;
- (void)captureSession:(id)arg1 destinationFragmentDurationDidChangeToDuration:(double)arg2 captureTime:(double)arg3 usingDisplayLinkSmoothing:(BOOL)arg4;
- (void)captureSession:(id)arg1 rateDidChangeToRate:(float)arg2;
- (void)captureSession:(id)arg1 didFinishWithSuccess:(BOOL)arg2;
- (void)_captureInputDeviceCaptureSessionDidChangeNotification:(id)arg1;
@property(readonly, nonatomic) RCWaveformDataSource *presentedWaveformDataSource;
- (void)_application:(id)arg1 willConnectCanvas:(id)arg2;
- (void)_delayedSelectRecordingWithUUID:(id)arg1;
- (void)applicationDidResume:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)activateApplication;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)removeDisplayLinkObserver:(id)arg1;
- (void)addDisplayLinkObserver:(id)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (unsigned long long)splitViewControllerSupportedInterfaceOrientations:(id)arg1;
- (BOOL)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
@property(nonatomic) BOOL recordingCardPresented;
- (id)viewControllerForMainView;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)_askUserForPermissionToUseCloudKit:(CDUnknownBlockType)arg1;
- (void)_showWelcomeScreenWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_requestCloudKitAccountInfo;
- (void)_checkCloudAccountInfo:(id)arg1 error:(id)arg2;
- (void)manager:(id)arg1 error:(id)arg2;
- (void)manager:(id)arg1 locationsOfInterest:(id)arg2;
- (void)manager:(id)arg1 currentLocation:(id)arg2;
- (void)dealloc;
- (BOOL)isScrollingTest:(id)arg1;
- (BOOL)selectFirstVoiceMemoInTableView:(id)arg1 errorString:(id *)arg2;
- (void)performScrollTestForTableView:(id)arg1 withOptions:(id)arg2;
- (void)startScrollVoiceMemosEditListTest:(id)arg1;
- (void)startPlaySelectedVoiceMemoTest:(id)arg1;
- (void)startSelectFirstVoiceMemoInTableView:(id)arg1;
- (void)startRecordNewVoiceMemoTest:(id)arg1;
- (void)startScrollVoiceMemosListTest:(id)arg1;
- (void)startShowVoiceMemosListTest:(id)arg1 warm:(BOOL)arg2;
- (void)ppt_didStartVoiceMemoPreviewPlayback;
- (void)ppt_didStartRecording;
- (void)ppt_willLoadVoiceMemoIntoEditor;
- (void)ppt_didShowVoiceMemoEditor;
- (void)ppt_willShowVoiceMemoEditor;
- (void)ppt_didShowVoiceMemosList;
- (void)ppt_didFinishPostLaunchTasks:(id)arg1;
- (void)ppt_didFinishExtendedLaunch;
- (BOOL)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;
- (id)_recordingTableView;
- (id)currentSelectedRecordingCell;
- (id)_recordingViewController;
- (id)_mainViewController;
- (id)_uiNavigationController;
- (id)_uiSplitViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

