//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

@class NSButton, NSTextField;
@protocol AddPersonCollectionViewItemDelegate;

@interface AddPersonCollectionViewItem : NSCollectionViewItem
{
    BOOL _enabled;
    id <AddPersonCollectionViewItemDelegate> _delegate;
    NSButton *_addPersonButton;
    NSTextField *_addPersonLabel;
}

@property __weak NSTextField *addPersonLabel; // @synthesize addPersonLabel=_addPersonLabel;
@property __weak NSButton *addPersonButton; // @synthesize addPersonButton=_addPersonButton;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <AddPersonCollectionViewItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addPersonButtonPressed:(id)arg1;
- (void)viewDidLoad;

@end

