//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "CNAutocompleteFetchDelegate-Protocol.h"
#import "CNAutocompleteResultWindowDelegate-Protocol.h"
#import "DFRControllerDelegate-Protocol.h"
#import "NSGestureRecognizerDelegate-Protocol.h"
#import "NSTokenFieldCellDelegate-Protocol.h"
#import "NSTokenFieldDelegate-Protocol.h"

@class CNAutocompleteResult, CNAutocompleteStore, CNExtendedAutocompleteResultWindow, FTTokenField, NSClickGestureRecognizer, NSHashTable, NSMutableArray, NSMutableOrderedSet, NSStackView, NSString, NSTextField, NSVisualEffectView, RoundRectButton, TUSearchController, TUSearchResults;
@protocol AddPersonSearchViewControllerDelegate, CNCancelable;

@interface AddPersonSearchViewController : NSViewController <NSTokenFieldDelegate, NSTokenFieldCellDelegate, CNAutocompleteResultWindowDelegate, CNAutocompleteFetchDelegate, DFRControllerDelegate, NSGestureRecognizerDelegate>
{
    BOOL _userIsDeleting;
    BOOL _skipCompletionRebuilding;
    id <AddPersonSearchViewControllerDelegate> _peoplePickerDelegate;
    FTTokenField *_tokenField;
    NSStackView *_stackView;
    RoundRectButton *_cancelButton;
    RoundRectButton *_addPersonButton;
    NSClickGestureRecognizer *_clickGestureRecognizer;
    TUSearchController *_searchController;
    CDUnknownBlockType _searchCompletionBlock;
    CDUnknownBlockType _recentsCompletionBlock;
    TUSearchResults *_tokenResults;
    TUSearchResults *_searchResults;
    NSString *_searchString;
    CNExtendedAutocompleteResultWindow *_completionWindow;
    CNAutocompleteStore *_autocompleteStore;
    id <CNCancelable> _currentFetchRequest;
    long long _completionWindowLevel;
    NSHashTable *_tokenAttachmentCells;
    NSMutableArray *_autocompleteResults;
    NSMutableOrderedSet *_autoCompleteSearchResults;
    NSTextField *_addPersonLabel;
    CNAutocompleteResult *_selectedCompletionResult;
    NSVisualEffectView *_cancelButtonContainer;
    NSVisualEffectView *_addPersonContainer;
}

+ (id)idsDestinationsForHandle:(id)arg1;
+ (id)idsDestinationsForToken:(id)arg1;
+ (id)idsDestinationsForAutocompleteResult:(id)arg1;
@property __weak NSVisualEffectView *addPersonContainer; // @synthesize addPersonContainer=_addPersonContainer;
@property __weak NSVisualEffectView *cancelButtonContainer; // @synthesize cancelButtonContainer=_cancelButtonContainer;
@property(retain, nonatomic) CNAutocompleteResult *selectedCompletionResult; // @synthesize selectedCompletionResult=_selectedCompletionResult;
@property __weak NSTextField *addPersonLabel; // @synthesize addPersonLabel=_addPersonLabel;
@property(copy, nonatomic) NSMutableOrderedSet *autoCompleteSearchResults; // @synthesize autoCompleteSearchResults=_autoCompleteSearchResults;
@property(readonly, copy, nonatomic) NSMutableArray *autocompleteResults; // @synthesize autocompleteResults=_autocompleteResults;
@property(readonly, nonatomic) NSHashTable *tokenAttachmentCells; // @synthesize tokenAttachmentCells=_tokenAttachmentCells;
@property(nonatomic) BOOL skipCompletionRebuilding; // @synthesize skipCompletionRebuilding=_skipCompletionRebuilding;
@property(nonatomic) long long completionWindowLevel; // @synthesize completionWindowLevel=_completionWindowLevel;
@property(nonatomic) BOOL userIsDeleting; // @synthesize userIsDeleting=_userIsDeleting;
@property(retain, nonatomic) id <CNCancelable> currentFetchRequest; // @synthesize currentFetchRequest=_currentFetchRequest;
@property(readonly, nonatomic) CNAutocompleteStore *autocompleteStore; // @synthesize autocompleteStore=_autocompleteStore;
@property(retain, nonatomic) CNExtendedAutocompleteResultWindow *completionWindow; // @synthesize completionWindow=_completionWindow;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(retain, nonatomic) TUSearchResults *searchResults; // @synthesize searchResults=_searchResults;
@property(retain, nonatomic) TUSearchResults *tokenResults; // @synthesize tokenResults=_tokenResults;
@property(copy, nonatomic) CDUnknownBlockType recentsCompletionBlock; // @synthesize recentsCompletionBlock=_recentsCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType searchCompletionBlock; // @synthesize searchCompletionBlock=_searchCompletionBlock;
@property(retain, nonatomic) TUSearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) NSClickGestureRecognizer *clickGestureRecognizer; // @synthesize clickGestureRecognizer=_clickGestureRecognizer;
@property __weak RoundRectButton *addPersonButton; // @synthesize addPersonButton=_addPersonButton;
@property __weak RoundRectButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property __weak NSStackView *stackView; // @synthesize stackView=_stackView;
@property __weak FTTokenField *tokenField; // @synthesize tokenField=_tokenField;
@property(nonatomic) __weak id <AddPersonSearchViewControllerDelegate> peoplePickerDelegate; // @synthesize peoplePickerDelegate=_peoplePickerDelegate;
- (void).cxx_destruct;
- (void)DFRController:(id)arg1 selectedAutoCompleteAtIndex:(long long)arg2;
- (void)DFRController:(id)arg1 performedActionType:(unsigned long long)arg2 withData:(id)arg3;
- (BOOL)isMultiwayAllowedForCurrentRecipients;
- (void)controlTextDidChange:(id)arg1;
- (id)_strippedPboardString:(id)arg1;
- (id)tokenField:(id)arg1 readFromPasteboard:(id)arg2;
- (struct _NSRange)rangeForUserCompletionInFieldEditor:(id)arg1;
- (id)autocompleteStringForFieldEditor:(id)arg1;
- (void)_registerTokenAttachmentCell:(id)arg1;
- (id)addressStringForResult:(id)arg1;
- (unsigned long long)indexOfSelectedCompletionResult;
- (void)_updateAutoCompleteUI;
- (void)autocompleteFetchDidFinish:(id)arg1;
- (void)autocompleteFetch:(id)arg1 didFailWithError:(id)arg2;
- (void)autocompleteFetch:(id)arg1 didReceiveResults:(id)arg2;
- (void)dismissCompletionUI;
- (id)handleForChosenCompletionResult:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)selectedResult:(id)arg1;
- (void)didSelectResult:(id)arg1;
- (BOOL)selectCurrentResult;
- (void)refreshDFRState;
- (void)showCompletions;
- (void)updateWindowLocation;
- (void)completionWindowDidResize:(id)arg1;
- (void)selectCurrentResultUsingHighlightedResult;
@property(readonly, nonatomic) BOOL showingCompletionWindow;
- (void)_startAutocompletion;
- (id)tokenField:(id)arg1 setUpTokenAttachmentCell:(id)arg2 forRepresentedObject:(id)arg3;
- (unsigned long long)tokenField:(id)arg1 styleForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 displayStringForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 shouldAddObjects:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)tokensFromTokenField;
- (id)tokenField:(id)arg1 representedObjectForEditingString:(id)arg2;
- (void)idsStatusChanged:(id)arg1;
- (void)focusSearchWithString:(id)arg1;
- (id)searchText;
- (void)addPersonButtonTapped:(id)arg1;
- (void)cancelButtonTapped:(id)arg1;
- (void)hideControlsForEmptySearchString;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleClickGesture:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

