//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVControllerDelegateProtocol-Protocol.h"
#import "DFRControllerDelegate-Protocol.h"
#import "NSSharingServiceDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"
#import "SODarkWakeHelperDelegate-Protocol.h"

@class FTCallController, FTOutgoingCallInfo, NSMutableArray, NSString, SODarkWakeHelper, TUCallCenter;

@interface AVControllerManager : NSObject <NSWindowDelegate, SODarkWakeHelperDelegate, AVControllerDelegateProtocol, NSSharingServiceDelegate, DFRControllerDelegate>
{
    BOOL _makingCall;
    BOOL _acceptingCallWaiting;
    BOOL _faceTimeCallRingSuppressed;
    BOOL _ringMuteHandlerStarted;
    BOOL _bypassStoringCall;
    unsigned int _invitationAssertionID;
    unsigned int _displaySleepAssertionID;
    NSMutableArray *_videoCallControllers;
    NSString *_remoteiMessageAddress;
    FTCallController *_callController;
    FTOutgoingCallInfo *_storedCall;
    TUCallCenter *_callCenter;
    NSMutableArray *_multiwayVideoCallWindowControllers;
    SODarkWakeHelper *_darkWakeHelper;
}

+ (void)queryiMessageRepliability:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
+ (id)sharedInstance;
@property(readonly, nonatomic) SODarkWakeHelper *darkWakeHelper; // @synthesize darkWakeHelper=_darkWakeHelper;
@property(readonly, nonatomic) NSMutableArray *multiwayVideoCallWindowControllers; // @synthesize multiwayVideoCallWindowControllers=_multiwayVideoCallWindowControllers;
@property(retain, nonatomic) TUCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(nonatomic) unsigned int displaySleepAssertionID; // @synthesize displaySleepAssertionID=_displaySleepAssertionID;
@property(nonatomic) unsigned int invitationAssertionID; // @synthesize invitationAssertionID=_invitationAssertionID;
@property(nonatomic) BOOL bypassStoringCall; // @synthesize bypassStoringCall=_bypassStoringCall;
@property(retain, nonatomic) FTOutgoingCallInfo *storedCall; // @synthesize storedCall=_storedCall;
@property(nonatomic) BOOL ringMuteHandlerStarted; // @synthesize ringMuteHandlerStarted=_ringMuteHandlerStarted;
@property(nonatomic) BOOL faceTimeCallRingSuppressed; // @synthesize faceTimeCallRingSuppressed=_faceTimeCallRingSuppressed;
@property(nonatomic) BOOL acceptingCallWaiting; // @synthesize acceptingCallWaiting=_acceptingCallWaiting;
@property(nonatomic) BOOL makingCall; // @synthesize makingCall=_makingCall;
@property(readonly, nonatomic) FTCallController *callController; // @synthesize callController=_callController;
@property(retain, nonatomic) NSString *remoteiMessageAddress; // @synthesize remoteiMessageAddress=_remoteiMessageAddress;
@property(retain, nonatomic) NSMutableArray *videoCallControllers; // @synthesize videoCallControllers=_videoCallControllers;
- (void).cxx_destruct;
- (void)externalDisplayAttached;
- (void)clamshellOpened;
- (void)screenShieldWasRaised;
- (void)screenShieldWasLowered;
- (void)lockScreenWillBeDisplayed;
@property(readonly, nonatomic) long long activeVideoCallControllerCount;
- (void)DFRController:(id)arg1 performedActionType:(unsigned long long)arg2 withData:(id)arg3;
- (BOOL)DFRControllerIsFullScreen;
- (void)controller:(id)arg1 windowWillClose:(id)arg2;
- (void)updateWindowLevels;
- (BOOL)contactListIsVisible;
- (void)presentUIForPreExistingCall:(id)arg1;
- (void)_getConnectedState:(char *)arg1 disconnectedState:(char *)arg2 forCall:(id)arg3;
- (BOOL)shouldTerminateOnLastWindowClosed;
- (void)initiateStoredCall;
- (BOOL)hasStoredOutgoingCall;
- (void)makeOutgoingCallWithInfo:(id)arg1;
- (void)makePhoneCallTo:(id)arg1 abRecordID:(id)arg2 ttyType:(long long)arg3 showPrompt:(BOOL)arg4;
- (void)makeCallToDestinations:(id)arg1 isAudio:(BOOL)arg2;
- (void)joinConversationWithRemoteMembers:(id)arg1 isAudio:(BOOL)arg2 wantsStagingArea:(BOOL)arg3;
- (void)joinConversationWithRemoteMembers:(id)arg1 wantsStagingArea:(BOOL)arg2;
- (void)joinConversationWithRemoteMembers:(id)arg1;
- (void)makeCallToDestination:(id)arg1 personID:(id)arg2 isAudio:(BOOL)arg3 showPrompt:(BOOL)arg4;
- (void)makeCallWithTUCall:(id)arg1;
- (void)makeCallWithDialRequest:(id)arg1;
- (void)receiveInvitationFrom:(id)arg1;
- (BOOL)shouldCreateProvisionalVideoCallControllerForCall:(id)arg1;
- (void)toggleAllPortraitLandscape;
- (void)_replyWithMessagePresented:(id)arg1;
- (void)_ncInternalDismissal:(id)arg1;
- (void)_callConnected:(id)arg1;
- (void)_accountEnabledStateChanged:(id)arg1;
- (void)_tuCallShouldSuppressRingingChanged:(id)arg1;
- (void)remoteParticipantHandlesChanged:(id)arg1;
- (void)createOrShowMultiwayControllerForCall:(id)arg1;
- (id)multiwayVideoCallWindowControllerForCall:(id)arg1;
- (void)cleanupWindowControllerForCall:(id)arg1;
- (id)videoCallControllerForCall:(id)arg1;
- (void)_tuCallStatusChanged:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)_setSystemMute:(BOOL)arg1;
- (void)_disableDisplayIdleSleep;
- (void)_enableDisplayIdleSleep;
- (void)_updateDisplayIdleSleep;
- (void)_silenceRingtoneIfNecessary;
- (void)_playRingtoneForCurrentControllerState;
- (BOOL)_notificationSoundEnabled;
- (void)_cancelInvitationAssertionID;
- (void)_stopRingMuteHandler;
- (void)_startRingMuteHandler;
- (void)_updateRingMuteHandler;
- (void)_handleAlertDismissal;
- (void)_handleAlertFailedToShow;
- (BOOL)_anyControllerPresent;
- (BOOL)hasController;
- (id)createVideoCallController;
- (void)closeNonCallVideoCallControllers;
- (void)ensureAndShowVideoCallController;
- (void)dismissAllPostCallUI;
- (void)dealloc;
- (void)_handleCallDowngradedToAudio:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

