//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "AddPersonCollectionViewItemDelegate-Protocol.h"
#import "CNContactPickerViewControllerDelegate-Protocol.h"
#import "CallDetailsCollectionViewItemDelegate-Protocol.h"
#import "NSCollectionViewDataSource-Protocol.h"
#import "NSCollectionViewDelegateFlowLayout-Protocol.h"
#import "SODarkWakeHelperDelegate-Protocol.h"

@class CNContactPickerViewController, NSCollectionView, NSString, NSVisualEffectView, SODarkWakeHelper, TUCall, TUContactsDataProvider;
@protocol SidebarContentDelegate;

@interface CallDetailsSideBarViewController : NSViewController <NSCollectionViewDataSource, CallDetailsCollectionViewItemDelegate, AddPersonCollectionViewItemDelegate, CNContactPickerViewControllerDelegate, NSCollectionViewDelegateFlowLayout, SODarkWakeHelperDelegate>
{
    TUCall *_call;
    id <SidebarContentDelegate> _delegate;
    NSCollectionView *_collectionView;
    NSVisualEffectView *_visualEffectView;
    CNContactPickerViewController *_contactPickerViewController;
    TUContactsDataProvider *_contactsDataProvider;
    SODarkWakeHelper *_darkWakeHelper;
}

+ (id)keysToFetch;
@property(retain, nonatomic) SODarkWakeHelper *darkWakeHelper; // @synthesize darkWakeHelper=_darkWakeHelper;
@property(retain, nonatomic) TUContactsDataProvider *contactsDataProvider; // @synthesize contactsDataProvider=_contactsDataProvider;
@property(retain, nonatomic) CNContactPickerViewController *contactPickerViewController; // @synthesize contactPickerViewController=_contactPickerViewController;
@property(retain, nonatomic) NSVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
@property __weak NSCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <SidebarContentDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TUCall *call; // @synthesize call=_call;
- (void).cxx_destruct;
- (void)externalDisplayAttached;
- (void)clamshellOpened;
- (void)lockScreenWillBeDisplayed;
- (void)screenShieldWasRaised;
- (void)screenShieldWasLowered;
- (void)handleCNContactStoreDidChangeNotification:(id)arg1;
- (void)contactPickerViewController:(id)arg1 didChooseContact:(id)arg2 key:(id)arg3 value:(id)arg4;
- (void)collectionViewItem:(id)arg1 addPersonButtonPressed:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionViewItem:(id)arg1 infoButtonPressed:(id)arg2;
- (void)presentCreateContactPopoverForDestinationID:(id)arg1 referenceView:(id)arg2;
- (void)viewWillLayout;
- (id)collectionView:(id)arg1 itemForRepresentedObjectAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

