//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

@class CNAvatarViewController, NSTextField, NSView;

@interface ConversationContactCollectionViewItem : NSCollectionViewItem
{
    NSTextField *_label;
    NSView *_avatarContainer;
    CNAvatarViewController *_avatarViewController;
}

+ (id)contactFormatter;
@property(retain, nonatomic) CNAvatarViewController *avatarViewController; // @synthesize avatarViewController=_avatarViewController;
@property(nonatomic) __weak NSView *avatarContainer; // @synthesize avatarContainer=_avatarContainer;
@property(nonatomic) __weak NSTextField *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)customizeCellWithContact:(id)arg1;
- (void)viewDidLoad;

@end

