//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "PersonTableRowView.h"

@class CHRecentCall, CNAvatarViewController, FTHighlightView, NSButton, NSImage, NSImageView, NSLayoutConstraint, NSTextField, NSView, VibrantBox;
@protocol TUSearchResult;

@interface ConversationRecentRowView : PersonTableRowView
{
    NSView *_avatarViewContainer;
    NSImageView *_faceTimeIconImageView;
    NSView *_secondAvatarViewContainer;
    NSButton *_audioButton;
    NSButton *_videoButton;
    NSTextField *_label;
    NSTextField *_dateLabel;
    VibrantBox *_bottomLine;
    NSLayoutConstraint *_dateLabelLeadingConstraint;
    CNAvatarViewController *_avatarViewController;
    CNAvatarViewController *_secondAvatarViewController;
    id <TUSearchResult> _rowItem;
    FTHighlightView *_highlightView;
    NSImage *_lightIconImage;
    NSImage *_darkIconImage;
}

+ (id)contactStore;
+ (id)contactFormatter;
+ (id)contactsForItem:(id)arg1;
+ (id)contactForHandle:(id)arg1 keyDescriptors:(id)arg2 recentCall:(id)arg3;
+ (id)formattedNameForHandle:(id)arg1 countryCode:(id)arg2;
+ (id)numberFormatter;
@property(retain, nonatomic) NSImage *darkIconImage; // @synthesize darkIconImage=_darkIconImage;
@property(retain, nonatomic) NSImage *lightIconImage; // @synthesize lightIconImage=_lightIconImage;
@property(retain, nonatomic) FTHighlightView *highlightView; // @synthesize highlightView=_highlightView;
@property(retain, nonatomic) id <TUSearchResult> rowItem; // @synthesize rowItem=_rowItem;
@property(retain, nonatomic) CNAvatarViewController *secondAvatarViewController; // @synthesize secondAvatarViewController=_secondAvatarViewController;
@property(retain, nonatomic) CNAvatarViewController *avatarViewController; // @synthesize avatarViewController=_avatarViewController;
@property(nonatomic) __weak NSLayoutConstraint *dateLabelLeadingConstraint; // @synthesize dateLabelLeadingConstraint=_dateLabelLeadingConstraint;
@property(nonatomic) __weak VibrantBox *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) __weak NSTextField *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) __weak NSTextField *label; // @synthesize label=_label;
@property(nonatomic) __weak NSButton *videoButton; // @synthesize videoButton=_videoButton;
@property(nonatomic) __weak NSButton *audioButton; // @synthesize audioButton=_audioButton;
@property(nonatomic) __weak NSView *secondAvatarViewContainer; // @synthesize secondAvatarViewContainer=_secondAvatarViewContainer;
@property(nonatomic) __weak NSImageView *faceTimeIconImageView; // @synthesize faceTimeIconImageView=_faceTimeIconImageView;
@property(nonatomic) __weak NSView *avatarViewContainer; // @synthesize avatarViewContainer=_avatarViewContainer;
- (void).cxx_destruct;
@property(readonly, nonatomic) CHRecentCall *recentCall;
- (void)setSearchResultItem:(id)arg1 recentsItem:(id)arg2;
- (void)awakeFromNib;

@end

