//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCandidateListTouchBarItemDelegate-Protocol.h"
#import "NSTouchBarAnimationDelegate-Protocol.h"
#import "NSTouchBarDelegate-Protocol.h"
#import "NSTouchBarProvider-Protocol.h"

@class CNContact, DFRCallParticipantViewController, DFRConversationParticipantsViewController, FTRecentsController, NSArray, NSButton, NSCandidateListTouchBarItem, NSCustomTouchBarItem, NSDictionary, NSMapTable, NSMutableDictionary, NSString, NSTouchBar, TUCallCenter, TUConversation, TUProxyRecentCall;
@protocol TUSearchResult;

@interface DFRController : NSObject <NSTouchBarAnimationDelegate, NSCandidateListTouchBarItemDelegate, NSTouchBarProvider, NSTouchBarDelegate>
{
    BOOL _replyWithMessageVisible;
    id <TUSearchResult> _selectedPerson;
    TUProxyRecentCall *_recentConversation;
    TUConversation *_selectedOnGoingConversation;
    CNContact *_selectedContactFromConversation;
    CNContact *_buzzableContactFromConversation;
    NSButton *_multiwayAudioButton;
    NSButton *_multiwayVideoButton;
    FTRecentsController *_recentsController;
    unsigned long long _DFRState;
    NSButton *_dialVideoItemButton;
    NSCandidateListTouchBarItem *_multiwayAutoCompleteTouchBarItem;
    DFRCallParticipantViewController *_callParticipantViewController;
    DFRConversationParticipantsViewController *_conversationParticipantsViewController;
    TUCallCenter *_callCenter;
    NSMutableDictionary *_identifierToViewMap;
    NSMutableDictionary *_identifierToWidthConstraintMap;
    NSTouchBar *_touchBar;
    NSTouchBar *_popoverTouchBar;
    NSCustomTouchBarItem *_popoverBarItem;
    NSDictionary *_buttonTitleDictionary;
    NSMapTable *_delegateToQueue;
    NSArray *_autoCompleteCandidates;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSArray *autoCompleteCandidates; // @synthesize autoCompleteCandidates=_autoCompleteCandidates;
@property(readonly, nonatomic) NSMapTable *delegateToQueue; // @synthesize delegateToQueue=_delegateToQueue;
@property(nonatomic) BOOL replyWithMessageVisible; // @synthesize replyWithMessageVisible=_replyWithMessageVisible;
@property(retain, nonatomic) NSDictionary *buttonTitleDictionary; // @synthesize buttonTitleDictionary=_buttonTitleDictionary;
@property(retain, nonatomic) NSCustomTouchBarItem *popoverBarItem; // @synthesize popoverBarItem=_popoverBarItem;
@property(retain, nonatomic) NSTouchBar *popoverTouchBar; // @synthesize popoverTouchBar=_popoverTouchBar;
@property(retain, nonatomic) NSTouchBar *touchBar; // @synthesize touchBar=_touchBar;
@property(retain, nonatomic) NSMutableDictionary *identifierToWidthConstraintMap; // @synthesize identifierToWidthConstraintMap=_identifierToWidthConstraintMap;
@property(retain, nonatomic) NSMutableDictionary *identifierToViewMap; // @synthesize identifierToViewMap=_identifierToViewMap;
@property(readonly, nonatomic) TUCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(retain, nonatomic) DFRConversationParticipantsViewController *conversationParticipantsViewController; // @synthesize conversationParticipantsViewController=_conversationParticipantsViewController;
@property(readonly, nonatomic) DFRCallParticipantViewController *callParticipantViewController; // @synthesize callParticipantViewController=_callParticipantViewController;
@property(retain, nonatomic) NSCandidateListTouchBarItem *multiwayAutoCompleteTouchBarItem; // @synthesize multiwayAutoCompleteTouchBarItem=_multiwayAutoCompleteTouchBarItem;
@property(retain, nonatomic) NSButton *dialVideoItemButton; // @synthesize dialVideoItemButton=_dialVideoItemButton;
@property(nonatomic) unsigned long long DFRState; // @synthesize DFRState=_DFRState;
@property(retain, nonatomic) FTRecentsController *recentsController; // @synthesize recentsController=_recentsController;
@property(retain, nonatomic) NSButton *multiwayVideoButton; // @synthesize multiwayVideoButton=_multiwayVideoButton;
@property(retain, nonatomic) NSButton *multiwayAudioButton; // @synthesize multiwayAudioButton=_multiwayAudioButton;
@property(retain, nonatomic) CNContact *buzzableContactFromConversation; // @synthesize buzzableContactFromConversation=_buzzableContactFromConversation;
@property(retain, nonatomic) CNContact *selectedContactFromConversation; // @synthesize selectedContactFromConversation=_selectedContactFromConversation;
@property(retain, nonatomic) TUConversation *selectedOnGoingConversation; // @synthesize selectedOnGoingConversation=_selectedOnGoingConversation;
@property(retain, nonatomic) TUProxyRecentCall *recentConversation; // @synthesize recentConversation=_recentConversation;
@property(retain, nonatomic) id <TUSearchResult> selectedPerson; // @synthesize selectedPerson=_selectedPerson;
- (void).cxx_destruct;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)candidateListTouchBarItem:(id)arg1 endSelectingCandidateAtIndex:(long long)arg2;
- (void)hideAutoCompleteResults;
- (void)showAutoCompleteResultsWithCandidates:(id)arg1;
- (void)updateButtonAppearance:(id)arg1;
- (void)showJoinConversationPrompt;
- (void)hideMultiwayPrompt;
- (void)showMultiwayPrompt;
- (void)showAudioCallPrompt;
- (void)showVideoCallPrompt;
- (id)emailAddressForSelectedParticipant:(id)arg1;
- (id)emailAddressesForConversation:(id)arg1;
- (id)emailAddressesForRecentConversation:(id)arg1;
- (id)emailAddressForSearchResult:(id)arg1;
- (void)performActionForType:(unsigned long long)arg1;
- (id)messageAddressesForCurrentState;
- (void)didSelectTouchBarItem:(id)arg1;
- (void)didSelectAudioMessageMailSegmentedControl:(id)arg1;
- (id)defaultFont;
- (BOOL)string:(id)arg1 withFont:(id)arg2 fitsWidth:(float)arg3;
- (id)determineButtonLayoutOverridesForIdentifiers:(id)arg1;
- (id)_createButtonWithTitle:(id)arg1 icon:(id)arg2 accessibilityLabel:(id)arg3 width:(float)arg4 action:(unsigned long long)arg5 color:(id)arg6 identifier:(id)arg7;
- (id)attributedWrappingButtonTitleFromString:(id)arg1;
- (id)_createWrappingButtonWithTitle:(id)arg1 accessibilityLabel:(id)arg2 width:(float)arg3 action:(unsigned long long)arg4 color:(id)arg5 identifier:(id)arg6;
- (id)buttonWithTitle:(id)arg1 icon:(id)arg2 accessibilityLabel:(id)arg3 width:(float)arg4 action:(unsigned long long)arg5 color:(id)arg6 identifier:(id)arg7 buttonLayoutOverrides:(id)arg8;
- (id)itemViewForItemIdentifier:(id)arg1 withButtonLayoutOverrides:(id)arg2;
- (id)groupItemForItemIdentifier:(id)arg1 withIdentifiers:(id)arg2 shouldApplyOverrides:(BOOL)arg3;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (void)_updateSnapshotState:(id)arg1;
- (void)_updateCameraOffButtonStateWithButton:(id)arg1;
- (void)_updateAudioMuteButtonStateWithButton:(id)arg1;
- (void)_updateMuteButtonStateWithButton:(id)arg1;
- (long long)cameraOffState;
- (long long)_muteState;
- (id)visibleTouchBar;
- (void)invalidateFunctionRowItems;
- (id)allItemIdentifiersForState:(unsigned long long)arg1;
- (id)itemIdentifiersForGroupIdentifier:(id)arg1;
- (id)itemIdentifiersForState:(unsigned long long)arg1 primaryIdentifier:(id *)arg2;
- (id)makeTouchBar;
- (void)updateTouchBarWithCurrentState:(id)arg1;
- (unsigned long long)stateForCallStatusChangeWithCall:(id)arg1;
- (void)_replyWithMessageDismissed:(id)arg1;
- (void)_replyWithMessagePresented:(id)arg1;
- (void)_updateWithCall:(id)arg1;
- (void)_tuCallStatusChanged:(id)arg1;
- (void)_tuCallVideoMuteChanged:(id)arg1;
- (void)_tuCallMuteChanged:(id)arg1;
- (void)_animateVideoUpgrade:(id)arg1;
- (void)_animateAudioCallAccept:(id)arg1;
- (void)_animateVideoCallAccept:(id)arg1;
- (BOOL)touchBar:(id)arg1 shouldAnimateFromIdentifiers:(id)arg2 toIdentifiers:(id)arg3;
- (void)_updateSegmentedControls;
- (void)_updateDialVideoItem;
- (void)_uninstallSystemTrayTouchBarItem;
- (void)_installSystemTrayTouchBarItem;
- (void)_dismissPopover;
- (void)_revealPopover;
- (void)_applicationBecameActive:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

