//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSClipView.h>

@class NSMutableArray;

@interface FTBorderedTextViewContainer : NSClipView
{
    double _textViewDisplayDuration;
    NSMutableArray *_textViews;
    NSMutableArray *_textViewVerticalContraints;
    NSMutableArray *_dismissalTimers;
}

@property(retain, nonatomic) NSMutableArray *dismissalTimers; // @synthesize dismissalTimers=_dismissalTimers;
@property(retain, nonatomic) NSMutableArray *textViewVerticalContraints; // @synthesize textViewVerticalContraints=_textViewVerticalContraints;
@property(retain, nonatomic) NSMutableArray *textViews; // @synthesize textViews=_textViews;
@property(nonatomic) double textViewDisplayDuration; // @synthesize textViewDisplayDuration=_textViewDisplayDuration;
- (void).cxx_destruct;
- (id)_dismissalTimerWithTextView:(id)arg1;
- (void)_rebuildVerticalConstraints;
- (id)textForViewAtIndex:(unsigned long long)arg1;
- (void)clearTextViews;
@property(readonly, nonatomic) unsigned long long numberOfTextViews;
- (void)addTextViewWithText:(id)arg1;
- (void)updateTextViewAtIndex:(unsigned long long)arg1 withText:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

