//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSTextField;

@interface FTBorderedTextView : NSView
{
    NSTextField *_textView;
}

+ (id)font;
@property(retain, nonatomic) NSTextField *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)layout;
- (id)text;
- (void)setText:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

