//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FTRecentsItem.h"

@class NSDate, NSDictionary, NSString;

@interface FTMutableRecentsItem : FTRecentsItem
{
}


// Remaining properties
@property(retain, nonatomic) NSDate *date; // @dynamic date;
@property(copy, nonatomic) NSDictionary *handlesToContacts; // @dynamic handlesToContacts;
@property(copy, nonatomic) NSString *localizedSubtitle; // @dynamic localizedSubtitle;
@property(copy, nonatomic) NSString *localizedTitle; // @dynamic localizedTitle;
@end

