//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSMutableCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSDate, NSDictionary, NSString;

@interface FTRecentsItem : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>
{
    NSString *_localizedSubtitle;
    NSString *_localizedTitle;
    NSDate *_date;
    NSDictionary *_handlesToContacts;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSDictionary *handlesToContacts; // @synthesize handlesToContacts=_handlesToContacts;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *localizedTitle; // @synthesize localizedTitle=_localizedTitle;
@property(copy, nonatomic) NSString *localizedSubtitle; // @synthesize localizedSubtitle=_localizedSubtitle;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithItem:(id)arg1;

@end

