//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TUCallProviderManagerDelegate-Protocol.h"

@class CNContactFormatter, CNContactStore, NSArray, NSCache, NSNumberFormatter, NSString, TUCallHistoryController, TUCallProviderManager, TUMetadataCache;
@protocol OS_dispatch_queue;

@interface FTRecentsController : NSObject <TUCallProviderManagerDelegate>
{
    TUCallHistoryController *_callHistoryController;
    NSCache *_callProviderCache;
    TUCallProviderManager *_callProviderManager;
    NSObject<OS_dispatch_queue> *_completionDispatchQueue;
    NSCache *_contactCache;
    CNContactFormatter *_contactFormatter;
    CNContactStore *_contactStore;
    NSCache *_itemCache;
    NSNumberFormatter *_numberFormatter;
    TUMetadataCache *_metadataCache;
    NSArray *_recentCalls;
    CNContactStore *_suggestedContactStore;
    unsigned long long _unreadCallCount;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

+ (id)contactStore;
+ (id)contactFormatter;
+ (id)contactForHandle:(id)arg1 keyDescriptors:(id)arg2 recentCall:(id)arg3;
+ (id)formattedNameForHandle:(id)arg1 countryCode:(id)arg2;
+ (id)numberFormatter;
+ (id)localizedDisplayStringForItem:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
- (void).cxx_destruct;
- (void)providersChangedForProviderManager:(id)arg1;
- (void)performSynchronousBlock:(CDUnknownBlockType)arg1;
- (void)handleTUMetadataCacheDidFinishUpdatingNotification:(id)arg1;
- (void)handleTUCallHistoryControllerUnreadCallCountDidChangeNotification:(id)arg1;
- (void)handleTUCallHistoryControllerRecentCallsDidChangeNotification:(id)arg1;
- (void)handleNSCurrentLocaleDidChangeNotification:(id)arg1;
- (void)handleIDSServiceAvailabilityDidChangeNotification:(id)arg1;
- (void)handleCNContactStoreDidChangeNotification:(id)arg1;
- (id)fetchRecentCalls;
- (id)fetchNumberFormatter;
- (void)fetchMetadataForRecentCalls:(id)arg1;
- (id)fetchContactFormatter;
@property(nonatomic) unsigned long long unreadCallCount; // @synthesize unreadCallCount=_unreadCallCount;
@property(copy, nonatomic) NSArray *recentCalls; // @synthesize recentCalls=_recentCalls;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(readonly, nonatomic) NSCache *itemCache; // @synthesize itemCache=_itemCache;
@property(retain, nonatomic) CNContactFormatter *contactFormatter; // @synthesize contactFormatter=_contactFormatter;
@property(readonly, nonatomic) NSCache *contactCache; // @synthesize contactCache=_contactCache;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *completionDispatchQueue; // @synthesize completionDispatchQueue=_completionDispatchQueue;
@property(readonly, nonatomic) NSCache *callProviderCache; // @synthesize callProviderCache=_callProviderCache;
@property(readonly, nonatomic) TUCallHistoryController *callHistoryController; // @synthesize callHistoryController=_callHistoryController;
- (id)formattedNameForHandle:(id)arg1 countryCode:(id)arg2;
- (id)contactForHandle:(id)arg1 keyDescriptors:(id)arg2 recentCall:(id)arg3;
- (id)contactForRecentCall:(id)arg1 keyDescriptors:(id)arg2;
- (void)markRecentAudioCallsAsRead;
- (void)markRecentCallsAsRead;
- (void)deleteRecentCalls:(id)arg1;
- (void)deleteAllRecentCalls;
- (BOOL)coalesceRecentCall:(id)arg1 withRecentCall:(id)arg2;
- (id)mostRecentCallInfoForCall:(id)arg1;
- (id)itemForRecentCall:(id)arg1;
@property(retain, nonatomic) TUMetadataCache *metadataCache; // @synthesize metadataCache=_metadataCache;
@property(retain, nonatomic) CNContactStore *suggestedContactStore; // @synthesize suggestedContactStore=_suggestedContactStore;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(retain, nonatomic) TUCallProviderManager *callProviderManager; // @synthesize callProviderManager=_callProviderManager;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

