//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTokenAttachmentCell.h>

#import "QLPreviewMenuItemDelegate-Protocol.h"

@class NSString, QLPreviewMenuItem;
@protocol FTTokenAttachmentCellDelegate;

@interface FTTokenAttachmentCell : NSTokenAttachmentCell <QLPreviewMenuItemDelegate>
{
    BOOL _alwaysDisplayBackground;
    id <FTTokenAttachmentCellDelegate> _delegate;
    QLPreviewMenuItem *_previewMenuItem;
}

@property(retain, nonatomic) QLPreviewMenuItem *previewMenuItem; // @synthesize previewMenuItem=_previewMenuItem;
@property BOOL alwaysDisplayBackground; // @synthesize alwaysDisplayBackground=_alwaysDisplayBackground;
@property(nonatomic) __weak id <FTTokenAttachmentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)drawTokenWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)alwaysShowBackground;
- (id)tokenTintColor;
- (struct CGRect)menuItem:(id)arg1 itemFrameForPoint:(struct CGPoint)arg2;
- (id)controlTokenField;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

