//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTokenField.h>

@class NSTrackingArea;

@interface FTTokenField : NSTokenField
{
    NSTrackingArea *_tokenFieldTrackingArea;
}

@property(retain, nonatomic) NSTrackingArea *tokenFieldTrackingArea; // @synthesize tokenFieldTrackingArea=_tokenFieldTrackingArea;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)awakeFromNib;
- (void)mouseExited:(id)arg1;
- (void)_tokenFieldDidChange:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;

@end

