//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNAutocompleteResult, NSString, TUHandle;
@protocol TUSearchResult;

@interface FTToken : NSObject
{
    id <TUSearchResult> _searchResult;
    NSString *_contactIdentifier;
    TUHandle *_handle;
    CNAutocompleteResult *_autoCompleteResult;
}

@property(retain, nonatomic) CNAutocompleteResult *autoCompleteResult; // @synthesize autoCompleteResult=_autoCompleteResult;
@property(retain, nonatomic) TUHandle *handle; // @synthesize handle=_handle;
@property(copy, nonatomic) NSString *contactIdentifier; // @synthesize contactIdentifier=_contactIdentifier;
@property(retain, nonatomic) id <TUSearchResult> searchResult; // @synthesize searchResult=_searchResult;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *localizedDisplayName;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

