//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FaceTimeNotificationCenterHostProtocol-Protocol.h"
#import "FaceTimeNotificationCenterServiceProtocol-Protocol.h"

@class NSMutableSet, NSXPCConnection;
@protocol OS_dispatch_queue;

@interface NCServiceConnection : NSObject <FaceTimeNotificationCenterServiceProtocol, FaceTimeNotificationCenterHostProtocol>
{
    BOOL _isConnected;
    NSXPCConnection *_xpcConnection;
    NSMutableSet *_alertUUIDSet;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) NSMutableSet *alertUUIDSet; // @synthesize alertUUIDSet=_alertUUIDSet;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property(nonatomic) BOOL isConnected; // @synthesize isConnected=_isConnected;
- (void).cxx_destruct;
@property(readonly) unsigned long long alertCount;
- (void)decrementAlertCount:(id)arg1;
- (void)incrementAlertCount:(id)arg1;
- (void)alertDismissedInternally:(id)arg1;
- (void)replyWithMessageUIDismissed;
- (void)replyWithMessageUIPresented;
- (void)dialForAllAlertsWithCallPromptUI;
- (void)cancelForAllAlertsWithCallPromptUI;
- (void)callBackForAllAlertsWithPostCallUI;
- (void)dismissPostCallUIForAllAlerts;
- (void)mergeForCallWithUniqueProxyIdentifier:(id)arg1;
- (void)swapForCallWithUniqueProxyIdentifier:(id)arg1;
- (void)sendReplyWithMessageUIForCallWithUniqueProxyIdentifier:(id)arg1;
- (void)dismissReplyWithMessageUIForCallWithUniqueProxyIdentifier:(id)arg1;
- (void)presentReplyWithMessageUIForCallWithUniqueProxyIdentifier:(id)arg1;
- (void)makeAlertWithUniqueProxyIdentifier:(id)arg1 adoptCallWithUniqueProxyIdentifier:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)makeAlertWithUniqueProxyIdentifier:(id)arg1 addCallWithUniqueProxyIdentifier:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)dismissAlertForCallWithUniqueProxyIdentifier:(id)arg1 animation:(unsigned long long)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)setShouldStopPreviewOnDealloc:(BOOL)arg1 forCallWithUniqueProxyIdentifier:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)screenFrameForCallWithUniqueProxyIdentifier:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)showAlertForCallWithUniqueProxyIdentifier:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)showAlertWithDialRequest:(id)arg1;
- (void)screenFrameWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)connect;
- (void)_waitForConnectionIfNecessaryWithBlock:(CDUnknownBlockType)arg1;
- (void)_handleInvalidation;
- (void)_handleInterruption;
- (void)_reconnect;
- (void)_setupConnection:(id)arg1;
- (void)_logAlertCount;
- (id)init;

@end

