//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "AddPersonSearchViewControllerDelegate-Protocol.h"
#import "SidebarContentDelegate-Protocol.h"

@class AddPersonSearchViewController, CallDetailsSideBarViewController, TUCall;

@interface SidebarContentViewController : NSViewController <SidebarContentDelegate, AddPersonSearchViewControllerDelegate>
{
    TUCall *_call;
    NSViewController *_containingViewController;
    CallDetailsSideBarViewController *_callDetailsSideBarViewController;
    AddPersonSearchViewController *_searchViewController;
}

@property(retain, nonatomic) AddPersonSearchViewController *searchViewController; // @synthesize searchViewController=_searchViewController;
@property(retain, nonatomic) CallDetailsSideBarViewController *callDetailsSideBarViewController; // @synthesize callDetailsSideBarViewController=_callDetailsSideBarViewController;
@property(nonatomic) __weak NSViewController *containingViewController; // @synthesize containingViewController=_containingViewController;
@property(retain, nonatomic) TUCall *call; // @synthesize call=_call;
- (void).cxx_destruct;
- (void)peoplePicker:(id)arg1 didAddAddresses:(id)arg2;
- (void)peoplePickerDidCancel:(id)arg1;
- (void)controllerDidSelectAddPerson:(id)arg1;
- (void)addPersonSearchViewController;
- (void)addCallDetailsSideBarViewController;
- (void)viewDidLoad;

@end

