//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class MLModelDescription, NSDictionary, NSObject, NSString;
@protocol MLCustomModel;

@protocol MLCustomModelFactory
- (NSObject<MLCustomModel> *)customModelWithName:(NSString *)arg1 modelDescription:(MLModelDescription *)arg2 parameterDictionary:(NSDictionary *)arg3 error:(id *)arg4;
@end

