//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MLInternalSettings : NSObject
{
    BOOL _restrictNeuralNetworksToUseCPUOnly;
    BOOL _restrictNeuralNetworksToUseNonEnergyEfficientMode;
    BOOL _experimentalMode;
    BOOL _isNeuralNetworkGPUPathForbidden;
    BOOL _isNeuralNetworkEnergyEfficientPathForbidden;
}

+ (id)globalSettings;
@property(readonly, nonatomic) BOOL isNeuralNetworkEnergyEfficientPathForbidden; // @synthesize isNeuralNetworkEnergyEfficientPathForbidden=_isNeuralNetworkEnergyEfficientPathForbidden;
@property(readonly, nonatomic) BOOL isNeuralNetworkGPUPathForbidden; // @synthesize isNeuralNetworkGPUPathForbidden=_isNeuralNetworkGPUPathForbidden;
@property BOOL experimentalMode; // @synthesize experimentalMode=_experimentalMode;
@property BOOL restrictNeuralNetworksToUseNonEnergyEfficientMode; // @synthesize restrictNeuralNetworksToUseNonEnergyEfficientMode=_restrictNeuralNetworksToUseNonEnergyEfficientMode;
@property BOOL restrictNeuralNetworksToUseCPUOnly; // @synthesize restrictNeuralNetworksToUseCPUOnly=_restrictNeuralNetworksToUseCPUOnly;
- (id)init;

@end

