//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@interface MLInt64ProbabilityDictionaryEnumerator : NSEnumerator
{
    __map_iterator_7eacffce _iter;
    __map_iterator_7eacffce _iterEnd;
}

+ (id)enumeratorFromMap:(map_f8690629 *)arg1;
@property(nonatomic) __map_iterator_7eacffce iterEnd; // @synthesize iterEnd=_iterEnd;
@property(nonatomic) __map_iterator_7eacffce iter; // @synthesize iter=_iter;
- (id).cxx_construct;
- (id)nextObject;
- (id)initWithIntMap:(map_f8690629 *)arg1;

@end

