//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreML/NSCopying-Protocol.h>

@interface MLModelConfiguration : NSObject <NSCopying>
{
    BOOL _useWatchSPIForScribble;
    long long _computeUnits;
}

+ (id)defaultConfiguration;
@property(nonatomic) BOOL useWatchSPIForScribble; // @synthesize useWatchSPIForScribble=_useWatchSPIForScribble;
@property long long computeUnits; // @synthesize computeUnits=_computeUnits;
- (unsigned long long)hash;
- (BOOL)isEqualToModelConfiguration:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithComputeUnits:(long long)arg1;

@end

