//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMStateCapture : NSObject
{
    CDUnknownBlockType _stateCaptureBlock;
    unsigned long long _handle;
}

@property(nonatomic) unsigned long long handle; // @synthesize handle=_handle;
@property(copy, nonatomic) CDUnknownBlockType stateCaptureBlock; // @synthesize stateCaptureBlock=_stateCaptureBlock;
- (void).cxx_destruct;
- (struct os_state_data_s *)stateDataForDictionary:(id)arg1 title:(id)arg2;
- (struct os_state_data_s *)_stateCapture;
- (void)unregisterHandlerforStateCapture;
- (void)registerHandlerforStateCapture;
- (void)dealloc;
- (id)init;

@end

