//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <FMCore/FMSystemInfo.h>

__attribute__((visibility("hidden")))
@interface FMSystemInfo_ios : FMSystemInfo
{
}

- (BOOL)hasSEP;
- (BOOL)isDeviceSecured;
- (id)btMacAddress;
- (id)wifiMacAddress;
- (id)chipId;
- (id)ecid;
- (id)meid;
- (id)imei;
- (id)serialNumber;
- (id)deviceModelName;
- (id)deviceName;
- (id)deviceUDID;
- (id)osBuildVersion;
- (id)osVersion;
- (id)deviceClass;
- (id)productName;
- (id)productType;
- (BOOL)_boolDeviceInfoForKey:(struct __CFString *)arg1;
- (id)_deviceInfoNumberForKey:(struct __CFString *)arg1;
- (id)_deviceInfoForKey:(struct __CFString *)arg1;

@end

