//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreCDPInternal/NSObject-Protocol.h>

@class CDPContext, NSDictionary, NSString;

@protocol CDPDSecureBackupProxy <NSObject>
@property(retain, nonatomic) CDPContext *cdpContext;
- (void)uncacheAllSecrets;
- (void)cacheRecoveryKey:(NSString *)arg1 completionBlock:(void (^)(NSError *))arg2;
- (void)enableWithInfo:(NSDictionary *)arg1 completionBlock:(void (^)(NSError *))arg2;
- (void)disableWithInfo:(NSDictionary *)arg1 completionBlock:(void (^)(NSError *))arg2;
- (NSDictionary *)recoverWithInfo:(NSDictionary *)arg1 error:(id *)arg2;
- (BOOL)enableWithInfo:(NSDictionary *)arg1 error:(id *)arg2;
- (BOOL)disableWithInfo:(NSDictionary *)arg1 error:(id *)arg2;
- (NSDictionary *)accountInfoWithInfo:(NSDictionary *)arg1 error:(id *)arg2;
- (id)init;
- (id)initWithContext:(CDPContext *)arg1;
@end

