//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreCDPInternal/CDPDAuthListener-Protocol.h>

@class CDPDFollowUpFactory, FLFollowUpController, NSString;

@interface CDPDFollowUpController : NSObject <CDPDAuthListener>
{
    FLFollowUpController *_followUpController;
    CDPDFollowUpFactory *_followUpFactory;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)securityLevelChanged:(BOOL)arg1;
- (BOOL)clearFollowUpWithContext:(id)arg1 error:(id *)arg2;
- (BOOL)postFollowUpItemForContext:(id)arg1 error:(id *)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

