//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "SPInfoViewController.h"

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"
#import "NSTouchBarDelegate-Protocol.h"
#import "NSTouchBarProvider-Protocol.h"
#import "SPInfoCollectionControllerDelegate-Protocol.h"

@class NSArray, NSGroupTouchBarItem, NSMapTable, NSObject, NSString, NSTableView, NSTouchBar, SPInfoCollectionController, SPInfoRecommendationTableCellView, SPInfoStaticRecommendation;

@interface SPInfoRecommendationsViewController : SPInfoViewController <NSTableViewDataSource, NSTableViewDelegate, SPInfoCollectionControllerDelegate, NSTouchBarProvider, NSTouchBarDelegate>
{
    long long _tbarOnce;
    NSTouchBar *_tbar;
    NSTouchBar *touchBar;
    NSTableView *_tableView;
    SPInfoCollectionController *_collectionController;
    SPInfoRecommendationTableCellView *_prototypeTableCellView;
    double _actionButtonWidth;
    NSObject *_topSeparatorMarker;
    NSObject *_middleSeparatorMarker;
    NSObject *_bottomSeparatorMarker;
    NSMapTable *_recommendationsByExtensionIdentifier;
    SPInfoStaticRecommendation *_storeIniCloudRecommendation;
    SPInfoStaticRecommendation *_enableiCloudDesktopAndDocumentsRecommendation;
    SPInfoStaticRecommendation *_enableiCloudPhotoLibraryRecommendation;
    SPInfoStaticRecommendation *_enableCloudKitMessagesRecommendation;
    SPInfoStaticRecommendation *_optimizeiCloudDesktopAndDocumentsRecommendation;
    SPInfoStaticRecommendation *_optimizeiCloudPhotoLibraryRecommendation;
    SPInfoStaticRecommendation *_optimizeStorageRecommendation;
    SPInfoStaticRecommendation *_emptyTrashAutomaticallyRecommendation;
    SPInfoStaticRecommendation *_reduceClutterRecommendation;
    NSArray *_tbarButtons;
    NSGroupTouchBarItem *_tbarGroup;
}

@property(retain) NSGroupTouchBarItem *tbarGroup; // @synthesize tbarGroup=_tbarGroup;
@property(retain) NSArray *tbarButtons; // @synthesize tbarButtons=_tbarButtons;
@property(retain) SPInfoStaticRecommendation *reduceClutterRecommendation; // @synthesize reduceClutterRecommendation=_reduceClutterRecommendation;
@property(retain) SPInfoStaticRecommendation *emptyTrashAutomaticallyRecommendation; // @synthesize emptyTrashAutomaticallyRecommendation=_emptyTrashAutomaticallyRecommendation;
@property(retain) SPInfoStaticRecommendation *optimizeStorageRecommendation; // @synthesize optimizeStorageRecommendation=_optimizeStorageRecommendation;
@property(retain) SPInfoStaticRecommendation *optimizeiCloudPhotoLibraryRecommendation; // @synthesize optimizeiCloudPhotoLibraryRecommendation=_optimizeiCloudPhotoLibraryRecommendation;
@property(retain) SPInfoStaticRecommendation *optimizeiCloudDesktopAndDocumentsRecommendation; // @synthesize optimizeiCloudDesktopAndDocumentsRecommendation=_optimizeiCloudDesktopAndDocumentsRecommendation;
@property(retain) SPInfoStaticRecommendation *enableCloudKitMessagesRecommendation; // @synthesize enableCloudKitMessagesRecommendation=_enableCloudKitMessagesRecommendation;
@property(retain) SPInfoStaticRecommendation *enableiCloudPhotoLibraryRecommendation; // @synthesize enableiCloudPhotoLibraryRecommendation=_enableiCloudPhotoLibraryRecommendation;
@property(retain) SPInfoStaticRecommendation *enableiCloudDesktopAndDocumentsRecommendation; // @synthesize enableiCloudDesktopAndDocumentsRecommendation=_enableiCloudDesktopAndDocumentsRecommendation;
@property(retain) SPInfoStaticRecommendation *storeIniCloudRecommendation; // @synthesize storeIniCloudRecommendation=_storeIniCloudRecommendation;
@property(retain) NSMapTable *recommendationsByExtensionIdentifier; // @synthesize recommendationsByExtensionIdentifier=_recommendationsByExtensionIdentifier;
@property(retain) NSObject *bottomSeparatorMarker; // @synthesize bottomSeparatorMarker=_bottomSeparatorMarker;
@property(retain) NSObject *middleSeparatorMarker; // @synthesize middleSeparatorMarker=_middleSeparatorMarker;
@property(retain) NSObject *topSeparatorMarker; // @synthesize topSeparatorMarker=_topSeparatorMarker;
@property double actionButtonWidth; // @synthesize actionButtonWidth=_actionButtonWidth;
@property(retain) SPInfoRecommendationTableCellView *prototypeTableCellView; // @synthesize prototypeTableCellView=_prototypeTableCellView;
@property(retain) SPInfoCollectionController *collectionController; // @synthesize collectionController=_collectionController;
@property NSTableView *tableView; // @synthesize tableView=_tableView;
@property(readonly) NSTouchBar *touchBar; // @synthesize touchBar;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (void)updateTouchbar;
- (id)subTouchBar;
- (void)rearrangeRecommendations;
- (id)makeUpdateServiceStatesOperation;
- (void)promptUserToSignInWithServiceIdentifiers:(id)arg1;
- (id)makeOptimizeCloudServicesOperationForRecommendations:(id)arg1;
- (id)makeEnableCloudServicesOperationForRecommendations:(id)arg1;
- (id)makeCloudKitMessagesOperationForRecommendations:(id)arg1;
- (id)longestActionButtonTitleInRecommendations:(id)arg1;
- (id)incompleteCloudServiceRecommendations;
- (void)recommendationsDidChange:(id)arg1;
- (void)operationDidFinish:(id)arg1;
- (void)collectionControllerDidArrangeObjects:(id)arg1;
- (void)collectionController:(id)arg1 didArrangeObject:(id)arg2 oldIndex:(unsigned long long)arg3 newIndex:(unsigned long long)arg4;
- (void)collectionControllerWillArrangeObjects:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (void)tableViewColumnDidResize:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)performReduceClutterRecommendationWithSender:(id)arg1;
- (void)performExtensionRecommendationWithSender:(id)arg1;
- (void)performOptimizeStorageRecommendationWithSender:(id)arg1;
- (void)performOptimizeiCloudPhotoLibraryRecommendationWithSender:(id)arg1;
- (void)performOptimizeiCloudDesktopAndDocumentsRecommendationWithSender:(id)arg1;
- (void)performEnableCloudKitMessagesRecommendationWithSender:(id)arg1;
- (void)performEnableiCloudPhotoLibraryRecommendationWithSender:(id)arg1;
- (void)performEnableiCloudDesktopAndDocumentsRecommendationWithSender:(id)arg1;
- (void)performStoreIniCloudRecommendationWithSender:(id)arg1;
- (void)performRecommendationWithSender:(id)arg1;
- (SEL)selectorForRecommendation:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

