//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CRKIfaddrs : NSObject
{
    struct ifaddrs *mIfaddrs;
}

@property(readonly, nonatomic) CRKIfaddrs *next;
@property(readonly, copy, nonatomic) NSString *IPAddress;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, nonatomic, getter=isInternetInterface) BOOL internetInterface;
- (id)initWithIfaddrs:(struct ifaddrs *)arg1;

@end

