//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface CRKSystemInfo : NSObject
{
    NSString *_buildVersion;
    NSString *_systemVersion;
}

+ (id)sharedSystemInfo;
@property(readonly, copy, nonatomic) NSString *systemVersion; // @synthesize systemVersion=_systemVersion;
@property(readonly, copy, nonatomic) NSString *buildVersion; // @synthesize buildVersion=_buildVersion;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDate *bootDate;
@property(readonly, nonatomic) unsigned long long platform;
- (void)populateVersions;
- (id)init;

@end

