//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ClassroomKit/NSObject-Protocol.h>

@class NSArray, NSDictionary;

@protocol CRKSettingsPaneInfoProvider <NSObject>
@property(readonly, nonatomic) NSDictionary *observingInstructorIdentifiersByCourseIdentifiers;
@property(readonly, copy, nonatomic) NSArray *courseInvitations;
@property(readonly, copy, nonatomic) NSArray *courses;
@end

