//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface CRKToolCommandUserInfo : NSObject
{
    NSString *_sessionIdentifier;
}

@property(readonly, copy, nonatomic) NSString *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
- (void).cxx_destruct;
- (id)appVersion;
@property(readonly, copy, nonatomic) NSDictionary *dictionaryValue;
- (id)initWithSessionIdentifier:(id)arg1;

@end

