//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSDateInterval.h>

@interface NSDateInterval (CRKAdditions)
- (id)crk_dateIntervalByAddingTimeInterval:(double)arg1;
@property(readonly, nonatomic) BOOL crk_containsCurrentDate;
@end

