//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSView (CSMAdditions)
+ (id)crk_autoLayoutContainerView;
- (void)crk_centerInSuperviewWithMargin:(double)arg1;
- (void)crk_pinDimensionsToLength:(double)arg1;
- (void)crk_pinToSize:(struct CGSize)arg1;
- (void)crk_safetyPinToSuperView;
- (void)crk_pinToSuperViewVertically;
- (void)crk_pinToSuperViewVerticallyWithMargin:(double)arg1;
- (void)crk_pinToSuperViewHorizontally;
- (void)crk_pinToSuperViewHorizontallyWithMargin:(double)arg1;
- (void)crk_pinToSuperView;
@end

