//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSSliderCell.h>

@class NSColor;

@interface ValidSubrangeSliderCell : NSSliderCell
{
    double _minValidValue;
    double _maxValidValue;
    NSColor *_validRangeBarColor;
}

@property double maxValidValue; // @synthesize maxValidValue=_maxValidValue;
@property double minValidValue; // @synthesize minValidValue=_minValidValue;
- (void).cxx_destruct;
- (BOOL)startTrackingAt:(struct CGPoint)arg1 inView:(id)arg2;
- (struct CGRect)_validSubrangeRect;
- (id)init;

@end

