//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

__attribute__((visibility("hidden")))
@interface OBPrivacyTextField : NSTextField
{
    BOOL _shouldBlockContextMenu;
}

@property BOOL shouldBlockContextMenu; // @synthesize shouldBlockContextMenu=_shouldBlockContextMenu;
- (id)textView:(id)arg1 menu:(id)arg2 forEvent:(id)arg3 atIndex:(unsigned long long)arg4;

@end

