//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSLayoutConstraint;

@interface ADPrivacyMarker : UIButton
{
    BOOL _isVideo;
    NSLayoutConstraint *_constraintHeight;
    NSLayoutConstraint *_constraintWidth;
}

+ (id)bundleForLocalizedString;
+ (id)deviceContentSize;
+ (id)dimensionsForVideoMarker;
+ (id)localizedLearnMoreText;
+ (id)localizedAdMarkerText;
@property(nonatomic) NSLayoutConstraint *constraintWidth; // @synthesize constraintWidth=_constraintWidth;
@property(nonatomic) NSLayoutConstraint *constraintHeight; // @synthesize constraintHeight=_constraintHeight;
@property(nonatomic) BOOL isVideo; // @synthesize isVideo=_isVideo;
- (void)dealloc;
- (id)accessibilityLabel;
- (id)accessibilityElements;
- (BOOL)isAccessibilityElement;
- (struct CGSize)intrinsicContentSize;
- (void)resetBannerMarkerForVideoMarker;
- (void)renderMarkerForBannerForCategory:(id)arg1 andLanguage:(BOOL)arg2;
- (void)updateAdMarkerSpec;
- (void)updateBackgroundAndTintColor;
- (id)init;

@end

