//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSString;
@protocol SAHandoffPayload;

@interface SAInitiateHandoffOnCompanion : SABaseClientBoundCommand
{
}

+ (id)initiateHandoffOnCompanionWithDictionary:(id)arg1 context:(id)arg2;
+ (id)initiateHandoffOnCompanion;
- (BOOL)requiresResponse;
@property(copy, nonatomic) NSString *notificationText;
@property(retain, nonatomic) id <SAHandoffPayload> handoffPayload;
@property(copy, nonatomic) NSString *dialogIdentifier;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

