//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <SAObjects/SAUISnippet.h>

@class NSString;

@interface SASUserUtteranceEditableTextSnippet : SAUISnippet
{
}

+ (id)userUtteranceEditableTextSnippetWithDictionary:(id)arg1 context:(id)arg2;
+ (id)userUtteranceEditableTextSnippet;
@property(copy, nonatomic) NSString *utterance;
@property(copy, nonatomic) NSString *sessionId;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

