//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSString, NSURL;

@interface SAVCSPlayContent : SABaseClientBoundCommand
{
}

+ (id)playContentWithDictionary:(id)arg1 context:(id)arg2;
+ (id)playContent;
- (BOOL)requiresResponse;
@property(copy, nonatomic) NSString *utsId;
@property(nonatomic) BOOL playTrailer;
@property(copy, nonatomic) NSURL *lowresTrailerUri;
@property(copy, nonatomic) NSURL *hiresTrailerUri;
@property(copy, nonatomic) NSString *contentType;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

