//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "CNARequestProbeResult-Protocol.h"
#import "CNATextFieldProtocol-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class CNARequest, CNATextField, NSButton, NSProgressIndicator, NSSegmentedControl, NSString, NSURL, NSURLCredential, NSView, WKWebView;

@interface CNAWindowController : NSWindowController <CNATextFieldProtocol, WKNavigationDelegate, WKUIDelegate, CNARequestProbeResult>
{
    BOOL _openNetworkFound;
    unsigned int _cookie;
    unsigned int _resultType;
    NSString *_interface;
    NSView *_controlsView;
    NSSegmentedControl *_navControl;
    NSProgressIndicator *_progressIndicator;
    NSButton *_lockButton;
    CNATextField *_URLTextField;
    NSButton *_cancelButton;
    WKWebView *_webView;
    NSURL *_url;
    CNARequest *_request;
    struct __CFURLStorageSession *_storageSession;
    NSURLCredential *_userAcceptedCredential;
}

@property(retain) NSURLCredential *userAcceptedCredential; // @synthesize userAcceptedCredential=_userAcceptedCredential;
@property struct __CFURLStorageSession *storageSession; // @synthesize storageSession=_storageSession;
@property BOOL openNetworkFound; // @synthesize openNetworkFound=_openNetworkFound;
@property unsigned int resultType; // @synthesize resultType=_resultType;
@property(retain) CNARequest *request; // @synthesize request=_request;
@property(retain) NSURL *url; // @synthesize url=_url;
@property WKWebView *webView; // @synthesize webView=_webView;
@property NSButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property CNATextField *URLTextField; // @synthesize URLTextField=_URLTextField;
@property NSButton *lockButton; // @synthesize lockButton=_lockButton;
@property NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property NSSegmentedControl *navControl; // @synthesize navControl=_navControl;
@property NSView *controlsView; // @synthesize controlsView=_controlsView;
@property unsigned int cookie; // @synthesize cookie=_cookie;
@property(copy) NSString *interface; // @synthesize interface=_interface;
- (void)dealloc;
- (void)windowDidLoad;
- (void)_addWebView;
- (void)navControlPressed:(id)arg1;
- (void)lockButtonPressed:(id)arg1;
- (void)cancelButtonPressed:(id)arg1;
- (void)promptForAllowingOpenURLs:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)informUserOfInsecureCaptiveNetwork;
- (void)URLTextFieldSelectableStateChanged:(BOOL)arg1;
- (void)_setURL:(id)arg1;
- (void)stopLoading;
- (void)loadRequest:(id)arg1;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)_updateWindowTitle;
- (void)probeFailed:(id)arg1 result:(int)arg2;
- (void)openNetworkFound:(id)arg1;
- (void)_prepareProbeWithRequest:(id)arg1;
- (void)_initiateProbeForRequest;
- (void)_setForwardButtonEnabled:(BOOL)arg1;
- (void)_setBackButtonEnabled:(BOOL)arg1;
- (void)_stopProgressIndicator;
- (void)_startProgressIndicator;
- (BOOL)_shouldAskAboutInsecureFormSubmission:(id)arg1;
- (void)_informUserOfInsecureFormSubmissionOnWindow:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_informUserOfInsecureLinkOnWindow:(id)arg1;
- (void)_reportURLError:(id)arg1 forRequest:(id)arg2;
- (void)_reportCertificateError:(id)arg1 forRequest:(id)arg2;
- (void)_errorAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_certificateTrustSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;
- (void)_updateLockButtonForURL:(id)arg1;
- (void)_showCertificateSheet:(id)arg1;
- (void)_certificateSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

