//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <SilexVideo/NSObject-Protocol.h>

@class UIGestureRecognizer;

@protocol SVGestureRecognizerManager <NSObject>
- (void)removeGestureRecognizer:(UIGestureRecognizer *)arg1;
- (void)addGestureRecognizer:(UIGestureRecognizer *)arg1;
@end

