//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SilexVideo/SVVideoControlVisibilityItem-Protocol.h>

@class NSString, UIView;

@interface SVVideoControlVisibilityItem : NSObject <SVVideoControlVisibilityItem>
{
    BOOL _hideable;
    UIView *_view;
}

@property(readonly, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) BOOL hideable; // @synthesize hideable=_hideable;
- (void).cxx_destruct;
- (void)hide:(BOOL)arg1 withAnimationCoordinator:(id)arg2;
- (BOOL)isVisible;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

