//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _ICPortraitUtilities : NSObject
{
}

+ (unsigned char)contactChangeTypeForPortraitChangeType:(unsigned char)arg1;
+ (id)contactFromPortraitContact:(id)arg1;
+ (id)contactRecordFromPortraitContactRecord:(id)arg1;
+ (unsigned char)namedEntityChangeTypeForPortraitNamedEntityChangeType:(unsigned char)arg1;
+ (unsigned char)namedEntityChangeTypeForPortraitEventChangeType:(unsigned char)arg1;
+ (id)namedEntityRecordFromPortraitNamedEntity:(id)arg1;
+ (id)namedEntityRecordsFromPortraitEventRecord:(id)arg1;

@end

