//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSActionCell.h>

@interface MicroButtonCell : NSActionCell
{
    long long _buttonType;
}

@property long long buttonType; // @synthesize buttonType=_buttonType;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawUnshadeWithFrame:(struct CGRect)arg1 stickiesWindow:(id)arg2;
- (void)drawZoomWithFrame:(struct CGRect)arg1 stickiesWindow:(id)arg2;
- (void)drawCloseWithFrame:(struct CGRect)arg1 stickiesWindow:(id)arg2;

@end

