//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HFUserNotificationCenter, NAFuture, NSURL;

@protocol HFUserNotificationPresentationHandling <NSObject>
- (void)notificationCenter:(HFUserNotificationCenter *)arg1 presentCustomSettingsForNotificationWithObjectURL:(NSURL *)arg2;
- (NAFuture *)notificationCenter:(HFUserNotificationCenter *)arg1 presentNotificationWithObjectURL:(NSURL *)arg2;
@end

