//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Home/HFItemManager.h>

@class HFItem, HFStaticItemProvider, HFTriggerItemProvider, HOAddTriggerItem, HOTriggerListSubheadlineItem;

@interface HOTriggerListItemManager : HFItemManager
{
    HFItem *_headlineItem;
    HOTriggerListSubheadlineItem *_subheadlineItem;
    HOAddTriggerItem *_addTriggerItem;
    HFStaticItemProvider *_staticItemProvider;
    HFTriggerItemProvider *_triggerItemProvider;
}

@property(retain, nonatomic) HFTriggerItemProvider *triggerItemProvider; // @synthesize triggerItemProvider=_triggerItemProvider;
@property(retain, nonatomic) HFStaticItemProvider *staticItemProvider; // @synthesize staticItemProvider=_staticItemProvider;
@property(retain, nonatomic) HOAddTriggerItem *addTriggerItem; // @synthesize addTriggerItem=_addTriggerItem;
@property(retain, nonatomic) HOTriggerListSubheadlineItem *subheadlineItem; // @synthesize subheadlineItem=_subheadlineItem;
@property(retain, nonatomic) HFItem *headlineItem; // @synthesize headlineItem=_headlineItem;
- (void).cxx_destruct;
- (id)_currentSectionIdentifiers;
- (id)_sectionIdentifierForItem:(id)arg1;
- (id)_identifierForSection:(unsigned long long)arg1;
- (unsigned long long)_numberOfSections;
- (id)_buildItemProvidersForHome:(id)arg1;

@end

