//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (CHExtensions)
- (id)ch_descriptionWithSeparator:(id)arg1 filterBlock:(CDUnknownBlockType)arg2;
- (id)ch_mappedArrayWithBlock:(CDUnknownBlockType)arg1;
@end

