//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NRRegistryQueryCompletionBlockEntry : NSObject
{
    CDUnknownBlockType _block;
    unsigned long long _updateCounter;
}

@property(nonatomic) unsigned long long updateCounter; // @synthesize updateCounter=_updateCounter;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (id)initWithUpdateCounter:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;

@end

