//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface BCLinkPresentationPropertiesProvider : NSObject
{
}

+ (id)presentationPropertiesForUnknownMessage:(id)arg1;
+ (id)presentationPropertiesForMessage:(id)arg1 andInternalAuthenticationManager:(id)arg2;
+ (id)presentationPropertiesForAuthenticationMessage:(id)arg1;
+ (id)presentationPropertiesForMessage:(id)arg1 andApplePayStatus:(long long)arg2;
+ (id)presentationPropertiesForMessage:(id)arg1;

@end

