//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <login/NSXPCListenerDelegate-Protocol.h>

@class LFListener, NSString;

@interface LFListenerDelegate : NSObject <NSXPCListenerDelegate>
{
    LFListener *_listener;
}

+ (id)delegateWithListener:(id)arg1;
@property(readonly) LFListener *listener; // @synthesize listener=_listener;
- (id)initWithListener:(id)arg1;
- (id)init;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

