//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSXPCInterface, NSXPCListener, NSXPCListenerEndpoint;
@protocol NSXPCListenerDelegate;

@interface LFListener : NSObject
{
    NSString *_serviceName;
    NSXPCListener *_listener;
    id <NSXPCListenerDelegate> _listenerDelegate;
    id _messageHandler;
    NSXPCInterface *_interface;
}

@property(retain) NSXPCListener *listener; // @synthesize listener=_listener;
@property(retain) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(retain) id <NSXPCListenerDelegate> listenerDelegate; // @synthesize listenerDelegate=_listenerDelegate;
@property(retain) NSXPCInterface *interface; // @synthesize interface=_interface;
@property(retain) id messageHandler; // @synthesize messageHandler=_messageHandler;
- (void)dealloc;
- (id)initWithMachServiceName:(id)arg1;
- (id)initAnonymousListener;
@property(readonly) NSXPCListenerEndpoint *endpoint;
- (void)invalidate;
- (void)suspend;
- (void)resume;

@end

