//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <login/LFListener.h>

@class NSXPCInterface;
@protocol LFLogindListenerInterface;

@interface LFLogindListener : LFListener
{
    NSXPCInterface *_privilegedInterface;
}

@property(retain) NSXPCInterface *privilegedInterface; // @synthesize privilegedInterface=_privilegedInterface;
- (void)dealloc;
- (id)initWithMachServiceName:(id)arg1;
- (id)initWithMessageHandler:(id)arg1;
- (id)init;

// Remaining properties
@property(retain) id <LFLogindListenerInterface> messageHandler; // @dynamic messageHandler;

@end

