//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IntentsCore/NSObject-Protocol.h>

@class INImage;
@protocol INKeyImageProducing;

@protocol INKeyImageProducing <NSObject>
@property(readonly) INImage *_keyImage;
- (long long)_compareSubProducerOne:(id <INKeyImageProducing>)arg1 subProducerTwo:(id <INKeyImageProducing>)arg2;

@optional
- (BOOL)_isValidSubProducer:(id <INKeyImageProducing>)arg1;
@end

