//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNContactFormatter, CNContactStore;

@interface FMFContactUtility : NSObject
{
    CNContactStore *_contactStore;
    CNContactFormatter *_contactFormatter;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CNContactFormatter *contactFormatter; // @synthesize contactFormatter=_contactFormatter;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
- (void).cxx_destruct;
- (id)contactKeys;
- (id)findOptimalContactInContacts:(id)arg1;
- (id)getContactForHandle:(id)arg1 keysToFetch:(id)arg2;
- (id)getContactForHandle:(id)arg1;
- (id)displayNameForContact:(id)arg1 andHandle:(id)arg2;

@end

