//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CSReceiverServerPreferences;

@interface SpotlightSenderState : NSObject
{
    CSReceiverServerPreferences *_serverPreferences;
}

@property(readonly, nonatomic) CSReceiverServerPreferences *serverPreferences; // @synthesize serverPreferences=_serverPreferences;
- (void).cxx_destruct;
- (BOOL)clientDisabled:(long long)arg1;
- (void)_updateFromPreferences;
- (id)init;

@end

