//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

@class SISchemaClientAnyEvent, SISchemaClientEventMetadata;

@interface SIEventWrapper : PBCodable
{
    SISchemaClientEventMetadata *_metadata;
    SISchemaClientAnyEvent *_wrappedEvent;
}

@property(retain, nonatomic) SISchemaClientAnyEvent *wrappedEvent; // @synthesize wrappedEvent=_wrappedEvent;
@property(retain, nonatomic) SISchemaClientEventMetadata *metadata; // @synthesize metadata=_metadata;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)initWithTimestamp:(long long)arg1 timestampReferenceID:(id)arg2 eventType:(int)arg3 eventBody:(id)arg4;

@end

