//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface LUI2ViewController : NSViewController
{
    BOOL _enabled;
}

@property(getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
- (id)init;
- (void)loadView;
@property(readonly) BOOL isVisible;
@property(readonly) long long blendingMode;

@end

