//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <LoginUIKit/NSObject-Protocol.h>

@class NSImage, NSString;

@protocol LUI2UserListDelegate <NSObject>
- (BOOL)isOtherUser:(id)arg1;
- (BOOL)isGuestUser:(id)arg1;
- (BOOL)isUserLoggedIn:(id)arg1;
- (NSString *)detailsOfUser:(id)arg1;
- (NSString *)nameOfUser:(id)arg1;
- (NSImage *)pictureOfUser:(id)arg1;

@optional
- (void)userPressed:(id)arg1;
- (long long)indexOfUserMatchingSearchString:(NSString *)arg1;
@end

