//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <LoginUIKit/LUI2ViewController.h>

@class NSStackView;

@interface LUI2ButtonViewController : LUI2ViewController
{
    NSStackView *_stackView;
}

@property NSStackView *stackView; // @synthesize stackView=_stackView;
- (void)viewDidLoad;
- (void)loadView;
- (void)addButton:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)_updateBlendingMode:(id)arg1;

@end

