//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@interface LUI2ScrollView : NSScrollView
{
    BOOL _scrollingEnabled;
}

+ (BOOL)isCompatibleWithResponsiveScrolling;
@property BOOL scrollingEnabled; // @synthesize scrollingEnabled=_scrollingEnabled;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)scrollWheel:(id)arg1;
- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (id)accessibilityChildren;
- (void)_setupScrollView;

@end

