//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <MapKit/NSObject-Protocol.h>

@class UIColor, UIControl;

@protocol _MKCalloutAccessoryView <NSObject>

@optional
- (UIControl *)_mapkit_accessoryControlToExtendWithCallout;
- (void)_mapkit_setCalloutTextColor:(UIColor *)arg1;
@end

