//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <MapKit/_MKCalloutAccessoryView-Protocol.h>

@class NSString;
@protocol _MKCalloutAccessoryView;

__attribute__((visibility("hidden")))
@interface _MKCalloutAccessoryWrapperView : UIView <_MKCalloutAccessoryView>
{
    UIView<_MKCalloutAccessoryView> *_view;
}

- (void).cxx_destruct;
- (void)_mapkit_setCalloutTextColor:(id)arg1;
- (id)_mapkit_accessoryControlToExtendWithCallout;
- (struct CGSize)intrinsicContentSize;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

