//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSSet, NSString, NSURL, NSUUID;

@interface _CDAttachmentRecord : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) NSUUID *cloudIdentifier; // @dynamic cloudIdentifier;
@property(retain, nonatomic) NSString *contentText; // @dynamic contentText;
@property(retain, nonatomic) NSURL *contentURL; // @dynamic contentURL;
@property(retain, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property(retain, nonatomic) NSUUID *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSSet *interactions; // @dynamic interactions;
@property(nonatomic) long long sizeInBytes; // @dynamic sizeInBytes;
@property(retain, nonatomic) NSString *uti; // @dynamic uti;
@end

