//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _DKLocationApplicationActivityMetadataKey : NSObject
{
}

+ (id)displayName;
+ (id)URL;
+ (id)phoneNumbers;
+ (id)longitude;
+ (id)latitude;
+ (id)postalCode;
+ (id)subThoroughfare;
+ (id)fullyFormattedAddress;
+ (id)thoroughfare;
+ (id)locationName;
+ (id)country;
+ (id)stateOrProvince;
+ (id)city;

@end

