//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _DKSyncMetadataStorage : NSObject
{
}

+ (id)eventFromStartDate:(id)arg1 endDate:(id)arg2 bookmarkStreamName:(id)arg3 transportName:(id)arg4;
+ (id)eventFromFetchedWindow:(id)arg1 windowStreamName:(id)arg2 transportName:(id)arg3;
+ (id)bookmarkStreamNameWithSourceDeviceID:(id)arg1;
+ (id)windowStreamNameWithSourceDeviceID:(id)arg1;

@end

