//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class NSObject, NSString;
@protocol NSCoding;

@protocol _DKSimpleKeyValueStore
- (void)removeObjectForKey:(NSString *)arg1;
- (void)setObject:(NSObject<NSCoding> *)arg1 forKey:(NSString *)arg2;
- (NSObject *)objectForKey:(NSString *)arg1;
@end

