//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDSCKDatabase, NSString;

@interface IDSCKContainer : NSObject
{
    NSString *_containerIdentifier;
    IDSCKDatabase *_privateCloudDatabase;
    IDSCKDatabase *_publicCloudDatabase;
}

+ (id)containerWithIdentifier:(id)arg1;
+ (Class)__class;
@property(readonly, nonatomic) IDSCKDatabase *publicCloudDatabase; // @synthesize publicCloudDatabase=_publicCloudDatabase;
@property(readonly, nonatomic) IDSCKDatabase *privateCloudDatabase; // @synthesize privateCloudDatabase=_privateCloudDatabase;
@property(readonly) NSString *containerIdentifier; // @synthesize containerIdentifier=_containerIdentifier;
- (void).cxx_destruct;

@end

