//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDSFoundation/NSCopying-Protocol.h>
#import <IDSFoundation/NSObject-Protocol.h>
#import <IDSFoundation/NSSecureCoding-Protocol.h>

@class NSData, NSSet;

@protocol IDSDestinationProtocol <NSSecureCoding, NSCopying, NSObject>
- (NSData *)groupID;
- (NSSet *)destinationURIs;
@end

