//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDSFoundationLog : NSObject
{
}

+ (id)RealTimeEncryptionController;
+ (id)QRAllocator_oversized;
+ (id)SessionController;
+ (id)GlobalLinkZUDP;
+ (id)GlobalLink;
+ (id)Stun;
+ (id)QRAllocator;
+ (id)IDSDSession;
+ (id)IDSSession;
+ (id)xpc;
+ (id)utilities;
+ (id)bonjourDeliveryController;
+ (id)deliveryController;
+ (id)BTLink;
+ (id)encryptionController;
+ (id)OTRController;
+ (id)socketPairConnection;
+ (id)localDeliveryQueue;
+ (id)UTunConnection;
+ (id)query;
+ (id)delivery;
+ (id)groupCrypto;
+ (id)accountIdentity;
+ (id)cloudKit;

@end

