//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDSFoundation/IDSMPIdentity.h>

#import <IDSFoundation/NSSecureCoding-Protocol.h>

@interface IDSMPPublicLegacyIdentity : IDSMPIdentity <NSSecureCoding>
{
}

+ (struct _SecMPPublicIdentity *)_createPublicIdentityFromData:(id)arg1 error:(id *)arg2;
+ (BOOL)supportsSecureCoding;
+ (id)identityWithData:(id)arg1 error:(id *)arg2;
- (id)dataRepresentationWithError:(id *)arg1;
- (id)signAndProtectData:(id)arg1 withSigner:(id)arg2 error:(id *)arg3;
- (id)initWithPublicIdentity:(struct _SecMPPublicIdentity *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) struct _SecMPPublicIdentity *publicIdentity;

@end

