//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreSpeech/NSObject-Protocol.h>

@class CSAudioDecoder, NSData;

@protocol CSAudioDecoderDelegate <NSObject>
- (void)audioDecoderDidDecodePackets:(CSAudioDecoder *)arg1 buffer:(NSData *)arg2 remoteVAD:(NSData *)arg3 timestamp:(unsigned long long)arg4;
@end

