//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreSpeech/NSObject-Protocol.h>

@class CSAudioFileReader, NSData, NSError;

@protocol CSAudioFileReaderDelegate <NSObject>
- (void)audioFileReaderDidStopRecording:(CSAudioFileReader *)arg1 forReason:(long long)arg2;
- (void)audioFileReaderDidStartRecording:(CSAudioFileReader *)arg1 successfully:(BOOL)arg2 error:(NSError *)arg3;
- (void)audioFileReaderBufferAvailable:(CSAudioFileReader *)arg1 buffer:(NSData *)arg2 atTime:(unsigned long long)arg3;
@end

