//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreSpeech/NSObject-Protocol.h>

@class CSSpIdSpeakerVectorGenerator, NSData;

@protocol CSSpIdSpeakerVectorGeneratorDelegate <NSObject>

@optional
- (void)speakerVectorGenerator:(CSSpIdSpeakerVectorGenerator *)arg1 finishedWithFinalSpeakerVector:(NSData *)arg2 speakerVectorSize:(unsigned long long)arg3 processedAudioDurationMs:(unsigned long long)arg4;
- (void)speakerVectorGenerator:(CSSpIdSpeakerVectorGenerator *)arg1 hasSpeakerVector:(NSData *)arg2 speakerVectorSize:(unsigned long long)arg3 processedAudioDurationMs:(unsigned long long)arg4;
@end

