//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSVoiceTriggerInfo : NSObject
{
    long long _firstPassRunningMode;
}

+ (id)sharedInstance;
@property(nonatomic) long long firstPassRunningMode; // @synthesize firstPassRunningMode=_firstPassRunningMode;
- (id)init;

@end

