//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreSpeech/NSObject-Protocol.h>

@class CSVTUITrainingSession, NSData, NSString;

@protocol CSVTUITrainingSessionDelegate <NSObject>
- (void)CSVTUITrainingSessionStopListen;
- (void)CSVTUITrainingSessionRMSAvailable:(float)arg1;

@optional
- (BOOL)CSVTUITrainingSession:(CSVTUITrainingSession *)arg1 hasTrainUtterance:(NSData *)arg2 languageCode:(NSString *)arg3 payload:(BOOL)arg4;
@end

