//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <CoreTelephony/CTXPCServiceSubscriptionContext.h>

#import <TelephonyUtilities/TUTelephonySubscription-Protocol.h>

@class NSString, NSUUID;

@interface CTXPCServiceSubscriptionContext (TelephonyUtilities) <TUTelephonySubscription>

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *labelID;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSUUID *uuid;
@end

