//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <TelephonyUtilities/NSObject-Protocol.h>

@class NSUUID;
@protocol TUCallHistoryManagerXPCClient;

@protocol TUCallHistoryManagerXPCServer <NSObject>
- (void)unregisterClient:(id <TUCallHistoryManagerXPCClient>)arg1;
- (void)registerClient:(id <TUCallHistoryManagerXPCClient>)arg1;
- (oneway void)updateOutgoingLocalParticipantUUID:(NSUUID *)arg1 forCallsWithOutgoingLocalParticipantUUID:(NSUUID *)arg2;
@end

