//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TUDTMFSoundPlayer : NSObject
{
    CDUnknownBlockType _playSystemSoundHandler;
}

@property(copy, nonatomic) CDUnknownBlockType playSystemSoundHandler; // @synthesize playSystemSoundHandler=_playSystemSoundHandler;
- (void).cxx_destruct;
- (void)attemptToPlaySoundType:(long long)arg1;
- (BOOL)attemptToPlayKey:(unsigned char)arg1;
- (id)init;

@end

