//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <TelephonyUtilities/NSObject-Protocol.h>

@class TUMomentDescriptor, TUMomentsCapabilities;
@protocol TUMomentsControllerDataSource;

@protocol TUMomentsControllerDataSourceDelegate <NSObject>
- (void)serverDiedForDataSource:(id <TUMomentsControllerDataSource>)arg1;
- (void)dataSource:(id <TUMomentsControllerDataSource>)arg1 didReceiveLocallyRequestedMomentDescriptor:(TUMomentDescriptor *)arg2;
- (void)willCaptureRemoteRequestForDataSource:(id <TUMomentsControllerDataSource>)arg1;
- (void)dataSource:(id <TUMomentsControllerDataSource>)arg1 didUpdateCapabilities:(TUMomentsCapabilities *)arg2 forVideoStreamToken:(long long)arg3;
@end

