//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <TelephonyUtilities/NSObject-Protocol.h>

@class CALayer;

@protocol TURemoteVideoClient <NSObject>
- (void)setVideoLayer:(CALayer *)arg1 forMode:(int)arg2;
@end

