//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface AFMediaRemoteDeviceInfo : NSObject
{
    BOOL _lastFetchSucceeded;
    NSString *_routeIdentifier;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

+ (id)currentDevice;
@property(nonatomic) BOOL lastFetchSucceeded; // @synthesize lastFetchSucceeded=_lastFetchSucceeded;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(copy, nonatomic) NSString *routeIdentifier; // @synthesize routeIdentifier=_routeIdentifier;
- (void).cxx_destruct;
- (void)getRouteIdentifierWithCompletion:(CDUnknownBlockType)arg1;
- (void)_updateRouteIdentifierWithCompletion:(CDUnknownBlockType)arg1;
- (void)_activeDeviceInfoChanged:(id)arg1;
- (id)init;

@end

