//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Social/SLWebAuthRequest-Protocol.h>

@class NSArray, NSString;

@protocol SLWebAuthRequest_Internal <SLWebAuthRequest>
+ (NSArray *)_parametersForClientID:(NSString *)arg1 redirectURI:(NSString *)arg2 scope:(NSArray *)arg3 username:(NSString *)arg4;
@end

