//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface NPNameComponentsData : NSObject
{
    NSDictionary *_nameComponents;
}

- (void).cxx_destruct;
- (BOOL)collectionForEntry:(unsigned long long)arg1 contains:(id)arg2;
- (id)objectValueForEntry:(unsigned long long)arg1;
- (id)_keyForDataEntry:(unsigned long long)arg1;
- (id)init;

@end

