//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ADServiceUtilities : NSObject
{
}

+ (id)ADSizeForContainerSize:(id)arg1 availableSizes:(id)arg2;
+ (id)ADFrameThatFits:(id)arg1 device:(id)arg2 adType:(int)arg3 statusBarOrientationIsPortrait:(BOOL)arg4 orientationChanged:(BOOL)arg5;

@end

