//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface PKAuthenticatorEvaluationResponse : NSObject
{
    _Bool _biometricMatch;
    long long _result;
    NSString *_kextBlacklistVersion;
    NSData *_credential;
}

+ (id)responseWithResult:(long long)arg1 biometricMatch:(_Bool)arg2 credential:(id)arg3;
+ (id)responseWithResult:(long long)arg1;
@property(readonly, nonatomic) NSData *credential; // @synthesize credential=_credential;
@property(copy, nonatomic) NSString *kextBlacklistVersion; // @synthesize kextBlacklistVersion=_kextBlacklistVersion;
@property(readonly, nonatomic) _Bool biometricMatch; // @synthesize biometricMatch=_biometricMatch;
@property(readonly, nonatomic) long long result; // @synthesize result=_result;
- (void).cxx_destruct;

@end

