//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PCRemoteServiceDelegate-Protocol.h"

@protocol OS_dispatch_queue;

@interface PCRemoteServiceConnection : NSObject <PCRemoteServiceDelegate>
{
    NSObject<OS_dispatch_queue> *_target_queue;
}

+ (id)sharedConnection;
@property(retain) NSObject<OS_dispatch_queue> *target_queue; // @synthesize target_queue=_target_queue;
- (void).cxx_destruct;
- (void)queryLastChimePlay:(CDUnknownBlockType)arg1;
- (id)init;

@end

