//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface TLCapabilitiesManager : NSObject
{
    NSDictionary *_deviceCodeNameSimplicationMapping;
}

+ (id)sharedCapabilitiesManager;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isHomePod) BOOL homePod;
@property(readonly, nonatomic) NSString *simplifiedDeviceCodeName;
@property(readonly, nonatomic) NSString *deviceCodeName;
@property(readonly, nonatomic) BOOL hasUserGeneratedVibrationsCapability;
@property(readonly, nonatomic) BOOL hasVibratorCapability;
@property(readonly, nonatomic, getter=isAlertToneStoreAvailable) BOOL alertToneStoreAvailable;
@property(readonly, nonatomic, getter=isRingtoneStoreAvailable) BOOL ringtoneStoreAvailable;
- (void)dealloc;
- (id)init;

@end

