//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC8FMClient24AuthenticationCredential : NSObject
{
    // Error parsing type: , name: authToken
    // Error parsing type: , name: personId
    // Error parsing type: , name: hostName
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithAuthToken:(id)arg1 personId:(id)arg2 hostName:(id)arg3;
@property(nonatomic, readonly) NSString *hostName; // @synthesize hostName;
@property(nonatomic, readonly) NSString *personId; // @synthesize personId;
@property(nonatomic, readonly) NSString *authToken; // @synthesize authToken;

@end

