//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <UIAccessibility/NSSecureCoding-Protocol.h>

@class NSArray, UIAccessibilityElementDescription;

@interface UIAccessibilityHierarchyDescription : NSObject <NSSecureCoding>
{
    UIAccessibilityElementDescription *_rootElement;
    NSArray *_leafElements;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSArray *leafElements; // @synthesize leafElements=_leafElements;
@property(retain, nonatomic) UIAccessibilityElementDescription *rootElement; // @synthesize rootElement=_rootElement;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

