//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (Hashing)
- (id)fm_hmac_sha512WithKey:(id)arg1;
- (id)fm_hmac_sha256WithKey:(id)arg1;
- (id)fm_hmac_sha1WithKey:(id)arg1;
- (id)fm_hmac_md5WithKey:(id)arg1;
@property(readonly, copy) NSData *fm_sha512Hash;
@property(readonly, copy) NSData *fm_sha256Hash;
@property(readonly, copy) NSData *fm_sha1Hash;
@property(readonly, copy) NSData *fm_md5Hash;
@end

