//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FindMyDevice/FMDIdentifiable-Protocol.h>
#import <FindMyDevice/NSCopying-Protocol.h>

@class NSString;

@interface FMDAccessoryIdentifier : NSObject <NSCopying, FMDIdentifiable>
{
    NSString *_string;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)stringValue;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (BOOL)isEqual:(id)arg1;
- (id)initWithString:(id)arg1;
- (id)computeAccessoryIdentifierWithAddress:(id)arg1;
- (id)initWithAddress:(id)arg1;
- (id)initWithDeviceVendor:(id)arg1 deviceProductId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

