//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <FindMyDevice/NSObject-Protocol.h>

@class FMDFMMAccountInfo, NSData, NSDictionary, NSString;

@protocol FMDFMMUAServicesProtocol <NSObject>
- (oneway void)addFMMAccount:(FMDFMMAccountInfo *)arg1 withAuthData:(NSData *)arg2 withReply:(void (^)(NSError *))arg3;
- (oneway void)resetShouldResumeCardsForUser:(NSString *)arg1 withReply:(void (^)(NSError *))arg2;
- (oneway void)didReceiveLostModeExitAuthToken:(NSString *)arg1 withReply:(void (^)(NSError *))arg2;
- (oneway void)updateAdditionalFMMAccountInfo:(NSDictionary *)arg1 withReply:(void (^)(NSError *))arg2;
- (oneway void)updateGUIDUsingAuthData:(NSData *)arg1 withReply:(void (^)(NSError *))arg2;
- (oneway void)clearLocateAlertsForCommandId:(NSString *)arg1 withReply:(void (^)(NSError *))arg2;
- (oneway void)getPendingLocateAlertsWithReply:(void (^)(NSString *, FMAlert *, FMAlert *, FMAlert *, NSError *))arg1;
@end

