//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <FindMyDevice/NSCopying-Protocol.h>
#import <FindMyDevice/NSObject-Protocol.h>
#import <FindMyDevice/NSSecureCoding-Protocol.h>

@class NSString;

@protocol FMDIdentifiable <NSObject, NSCopying, NSSecureCoding>
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (NSString *)stringValue;
@end

