//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FindMyDevice/NSSecureCoding-Protocol.h>

@class NSData;

@interface FMDIdentitySigningRequest : NSObject <NSSecureCoding>
{
    BOOL _useSCRT;
    NSData *_dataToSign;
    long long _validityInMinutes;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) long long validityInMinutes; // @synthesize validityInMinutes=_validityInMinutes;
@property(nonatomic) BOOL useSCRT; // @synthesize useSCRT=_useSCRT;
@property(retain, nonatomic) NSData *dataToSign; // @synthesize dataToSign=_dataToSign;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithData:(id)arg1;

@end

