//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSString;

@protocol _INPBLocalDate <NSObject>
@property(nonatomic) BOOL hasYear;
@property(nonatomic) long long year;
@property(nonatomic) BOOL hasMonth;
@property(nonatomic) long long month;
@property(nonatomic) BOOL hasDayOfWeek;
@property(nonatomic) int dayOfWeek;
@property(nonatomic) BOOL hasDayOfMonth;
@property(nonatomic) long long dayOfMonth;
- (int)StringAsDayOfWeek:(NSString *)arg1;
- (NSString *)dayOfWeekAsString:(int)arg1;
@end

