//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSString;

@protocol _INPBVoiceCommandStepInfo <NSObject>
@property(readonly, nonatomic) BOOL hasName;
@property(copy, nonatomic) NSString *name;
@property(nonatomic) BOOL hasCategory;
@property(nonatomic) int category;
@property(readonly, nonatomic) BOOL hasApplicationIdentifier;
@property(copy, nonatomic) NSString *applicationIdentifier;
- (int)StringAsCategory:(NSString *)arg1;
- (NSString *)categoryAsString:(int)arg1;
@end

