//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSArray, _INPBTimer;

@protocol _INPBResumeTimerIntentResponse <NSObject>
+ (Class)resumedTimersType;
@property(readonly, nonatomic) unsigned long long resumedTimersCount;
@property(copy, nonatomic) NSArray *resumedTimers;
- (_INPBTimer *)resumedTimersAtIndex:(unsigned long long)arg1;
- (void)addResumedTimers:(_INPBTimer *)arg1;
- (void)clearResumedTimers;
@end

