//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSArray, _INPBTask, _INPBTaskList;

@protocol _INPBAddTasksIntentResponse <NSObject>
+ (Class)addedTasksType;
@property(readonly, nonatomic) BOOL hasModifiedTaskList;
@property(retain, nonatomic) _INPBTaskList *modifiedTaskList;
@property(readonly, nonatomic) unsigned long long addedTasksCount;
@property(copy, nonatomic) NSArray *addedTasks;
- (_INPBTask *)addedTasksAtIndex:(unsigned long long)arg1;
- (void)addAddedTasks:(_INPBTask *)arg1;
- (void)clearAddedTasks;
@end

