//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class _INPBAppNames, _INPBIntentVocabulary, _INPBLanguageTag;

@protocol _INPBLocalizedProject <NSObject>
@property(readonly, nonatomic) BOOL hasLanguage;
@property(retain, nonatomic) _INPBLanguageTag *language;
@property(readonly, nonatomic) BOOL hasIntentVocabulary;
@property(retain, nonatomic) _INPBIntentVocabulary *intentVocabulary;
@property(readonly, nonatomic) BOOL hasAppNames;
@property(retain, nonatomic) _INPBAppNames *appNames;
@end

