//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSString;

@protocol _INPBAppNames <NSObject>
@property(readonly, nonatomic) BOOL hasSpotlightName;
@property(copy, nonatomic) NSString *spotlightName;
@property(readonly, nonatomic) BOOL hasDisplayName;
@property(copy, nonatomic) NSString *displayName;
@property(readonly, nonatomic) BOOL hasAxSpokenName;
@property(copy, nonatomic) NSString *axSpokenName;
@property(readonly, nonatomic) BOOL hasAppName;
@property(copy, nonatomic) NSString *appName;
@end

