//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Intents/INIntentResolutionResult.h>

@interface INNoteContentResolutionResult : INIntentResolutionResult
{
}

+ (id)confirmationRequiredWithNoteContentToConfirm:(id)arg1;
+ (id)disambiguationWithNoteContentsToDisambiguate:(id)arg1;
+ (id)successWithResolvedNoteContent:(id)arg1;

@end

