//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (SocialUIAdditions)
+ (id)progressBarBusinessColor;
+ (id)progressBariMessageColor;
+ (id)progressBarSMSColor;
+ (id)mapViewContainerBorderColor;
+ (id)primaryContrastColorForBusinessChat:(id)arg1;
+ (id)secondaryBrandColorForBusinessChat:(id)arg1;
+ (id)primaryBrandColorForBusinessChat:(id)arg1;
+ (id)colorWithWebColor:(id)arg1;
+ (id)businessToFieldGray;
+ (id)iMessageBlue;
+ (id)borderlessControlBlue;
+ (id)messagesTintColor;
- (BOOL)isDarkColor;
- (id)webStringValue;
- (BOOL)isEqualToColor:(id)arg1;
@end

