//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNCountryInformation, NSString;

@interface PKCountryInformation : NSObject
{
    CNCountryInformation *_countryInformation;
    NSString *_localizedCountryName;
}

@property(copy, nonatomic) NSString *localizedCountryName; // @synthesize localizedCountryName=_localizedCountryName;
@property(retain, nonatomic) CNCountryInformation *countryInformation; // @synthesize countryInformation=_countryInformation;
- (void).cxx_destruct;

@end

