//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <MediaPlayer/MPRemotePlaybackQueue.h>

@class NSData, NSString;

@interface MPCustomDataPlaybackQueue : MPRemotePlaybackQueue
{
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) NSData *data;
@property(readonly, nonatomic) NSString *identifier;
- (id)description;
- (id)initWithIdentifier:(id)arg1 data:(id)arg2;

@end

