//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPMediaItemArtwork, NSData, NSString;

@interface MPNowPlayingInfoCenterArtworkContext : NSObject
{
    NSString *_artworkIdentifier;
    MPMediaItemArtwork *_artwork;
    NSData *_artworkData;
}

@property(retain, nonatomic) NSData *artworkData; // @synthesize artworkData=_artworkData;
@property(retain, nonatomic) MPMediaItemArtwork *artwork; // @synthesize artwork=_artwork;
@property(copy, nonatomic) NSString *artworkIdentifier; // @synthesize artworkIdentifier=_artworkIdentifier;
- (void).cxx_destruct;

@end

